baseurl: "/python"
url: "https://graalvm.org"
github: "oracle/graalpython"
language_version: 25.0.2
python_version: 3.12
name: GraalPy
permalink: pretty

audiences:
  - identifier: jvm
    name: JVM
  - identifier: python
    name: Python

plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - graal-languages-jekyll-theme

theme: graal-languages-jekyll-theme

sass:
  quiet_deps: true

exclude:
  - Gemfile
  - Gemfile.lock
