[[pyo3-ffi.rules]]
version = '>=0.28,<0.29'
patch = 'pyo3-ffi-0.28.patch'
license = 'Apache-2.0 OR MIT'

[[pyo3-ffi.rules]]
version = '==0.29.0'
patch = 'pyo3-ffi-0.29.0.patch'
license = 'Apache-2.0 OR MIT'
