# Copyright (c) 2025, 2026, Oracle and/or its affiliates. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# The Universal Permissive License (UPL), Version 1.0
#
# Subject to the condition set forth below, permission is hereby granted to any
# person obtaining a copy of this software, associated documentation and/or
# data (collectively the "Software"), free of charge and under any and all
# copyright rights in the Software, and any and all patent rights owned or
# freely licensable by each licensor hereunder covering either (i) the
# unmodified Software as contributed to or provided by such licensor, or (ii)
# the Larger Works (as defined below), to deal in both
#
# (a) the Software, and
#
# (b) any piece of software and/or hardware listed in the lrgrwrks.txt file if
# one is included with the Software each a "Larger Work" to which the Software
# is contributed by such licensors),
#
# without restriction, including without limitation the rights to copy, create
# derivative works of, display, perform, and distribute the Software and make,
# use, sell, offer for sale, import, export, have made, and have sold the
# Software and the Larger Work(s), and to sublicense the foregoing rights on
# either these or other terms.
#
# This license is subject to the following condition:
#
# The above copyright notice and either this complete permission notice or at a
# minimum a reference to the UPL must be included in all copies or substantial
# portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# ================================
#
# This script is used by ci to merge several report JSON files generated by unittests or retagger.
#
# ================================

import sys
import json
import glob
import argparse
from dataclasses import dataclass, asdict


@dataclass
class Test:
    name: str
    status: str
    duration: str


def read_report(path: str, status_filter: list[str]) -> list[Test]:
    tests = []
    try:
        with open(path) as f:
            report_tests = json.load(f)
            
            for test in report_tests:
                status = test['status'].lower()
                if not status_filter or any(s in status for s in status_filter):
                    tests.append(Test(
                        name=test['name'],
                        status=test['status'],
                        duration=test.get('duration')
                    ))
    except (json.JSONDecodeError, Exception) as e:
        print(f"Error reading {path}: {e}", file=sys.stderr)
    
    return tests


def merge_reports(source_dir: str, pattern: str, status_filter: list[str]) -> dict[str, Test]:
    merged_tests = {}
    
    path = f"{source_dir}/{pattern}"
    files = glob.glob(path, recursive=True)
    
    files = [file for file in files if file.endswith(".json")]
    
    if not files:
        print(f"No files found matching pattern: {path}")
        return merged_tests
    
    print(f"Merging {len(files)} reports")
    
    for file in files:
        tests = read_report(file, status_filter)
        
        for test in tests:
            if test.name not in merged_tests:
                merged_tests[test.name] = test
    
    return merged_tests


def export_reports(merged_tests: dict[str, Test], outfile: str, status_filter: list[str]):
    output = [asdict(test) for test in merged_tests.values()]
    
    with open(outfile, "w") as f:
        json.dump(output, f, indent=2)
    
    print(f"Merged {len(merged_tests)} tests to {outfile}")


def main(outfile: str, source_dir: str, pattern: str, status_filter: str):
    status_list = []
    if status_filter:
        status_list = [s.strip() for s in status_filter.split(',')]
    
    merged_tests = merge_reports(source_dir, pattern, status_list)
    export_reports(merged_tests, outfile, status_list)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Merge test report JSON files")
    parser.add_argument("--outfile", help="Output file name (optional)", default="reports-merged.json")
    parser.add_argument("--dir", help="Reports files directory (optional)", default=".")
    parser.add_argument("--pattern", default="*", help="Pattern matching for input files (optional)")
    parser.add_argument("--status-filter", default="", help="Comma-separated list of status to filter (optional)")

    args = parser.parse_args()
    main(
        outfile=args.outfile,
        source_dir=args.dir,
        pattern=args.pattern,
        status_filter=args.status_filter
    )
