#!/usr/bin/env bash

VAR_NAME="$1"
ARTIFACT_PATH="$2"

REAL_PATH=$(eval echo $ARTIFACT_PATH)

if [ -d "$REAL_PATH" ]; then

    export "$VAR_NAME"="$REAL_PATH"
    echo "$REAL_PATH"
    echo "$VAR_NAME"="$REAL_PATH" >> "$GITHUB_ENV"

    which python
    python --version
    echo $PATH
    ls -l mxbuild/linux-amd64/GRAALPY_NATIVE_STANDALONE/ || true
fi