[tox]
envlist = graalpy

[testenv]
deps =
    pytest==8.4.2
commands =
    pytest --assert=plain tests {posargs}

[testenv:graalpy]
basepython=graalpy
passenv =
  GRAALPY_LEFTPAD_FAIL
  GRAAL_PYTHON_ARGS
  GRAAL_PYTHON_VM_ARGS
  PIP_EXTRA_INDEX_URL
  PIP_INDEX_URL
  PIP_RETRIES
  PIP_TIMEOUT
  PIP_TRUSTED_HOST
