.PHONY: clean default

# do nothing by default
default:

# this is why this Makefile can be useful: 'mx clean' will call this
clean:
	rm -rf virtualenv
	rm -rf leftpad/dist
	rm -rf leftpad/build
	rm -rf leftpad/.tox
	rm -rf leftpad/src/leftpad.egg-info
	rm -rf leftpad/tests/__pycache__
