# Additional native-image arguments for optional GraalPy BouncyCastle support
Args = --features=com.oracle.graal.python.bouncycastle.BouncyCastleFeature -H:AdditionalSecurityProviders=org.bouncycastle.jce.provider.BouncyCastleProvider
