#!/usr/bin/env python3
#
# Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# The Universal Permissive License (UPL), Version 1.0
#
# Subject to the condition set forth below, permission is hereby granted to any
# person obtaining a copy of this software, associated documentation and/or
# data (collectively the "Software"), free of charge and under any and all
# copyright rights in the Software, and in any and all patent rights owned or
# freely licensable by each licensor hereunder covering either (i) the
# unmodified Software as contributed to or provided by such licensor, or (ii)
# the Larger Works (as defined below), to deal in both
#
# (a) the Software, and
#
# (b) any piece of software and/or hardware listed in the lrgrwrks.txt file if
# one is included with the Software each a "Larger Work" to which the Software
# is contributed by such licensors),
#
# without restriction, including without limitation the rights to copy, create
# derivative works of, display, perform, and distribute the Software and make,
# use, sell, offer for sale, import, export, have made, and have sold the
# Software and the Larger Work(s), and to sublicense the foregoing rights on
# either these or other terms.
#
# This license is subject to the following condition:
#
# The above copyright notice and either this complete permission notice or at a
# minimum a reference to the UPL must be included in all copies or substantial
# portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:
    from pip._vendor import tomli as tomllib  # pylint: disable=no-name-in-module


DEFAULT_OUTPUT = Path(__file__).resolve().parents[1] / "abi" / "abi3t-linux.txt"
LINUX_DISABLED_FEATURES = {"MS_WINDOWS", "Py_REF_DEBUG", "USE_STACKCHECK"}


def git_output(repository: Path, *arguments: str) -> str:
    return subprocess.check_output(
        ["git", "-C", str(repository), *arguments],
        text=True,
    ).strip()


def generate_manifest(repository: Path, source_ref: str) -> str:
    commit = git_output(repository, "rev-parse", f"{source_ref}^{{commit}}")
    source = git_output(repository, "show", f"{source_ref}:Misc/stable_abi.toml")
    stable_abi = tomllib.loads(source)

    symbols: list[tuple[str, str]] = []
    for item_kind, elf_kind in (("function", "FUNC"), ("data", "OBJECT")):
        for name, properties in stable_abi[item_kind].items():
            if properties.get("ifdef") not in LINUX_DISABLED_FEATURES:
                symbols.append((name, elf_kind))
    symbols.sort()

    lines = [
        "# Generated by scripts/generate_abi3t_manifest.py. Do not edit manually.",
        f"# Source: CPython {source_ref} ({commit})",
        "# Source file: Misc/stable_abi.toml",
        "# Target: Linux ABI3T (MS_WINDOWS, Py_REF_DEBUG, and USE_STACKCHECK disabled)",
        "# Format: <expected ELF symbol kind> <symbol name>",
        "",
    ]
    lines.extend(f"{kind} {name}" for name, kind in symbols)
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate the Linux ABI3T export manifest from CPython's stable_abi.toml",
    )
    parser.add_argument("cpython", type=Path, help="path to a CPython Git repository")
    parser.add_argument("--source-ref", default="v3.15.0rc1", help="pinned CPython Git ref")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    manifest = generate_manifest(args.cpython.resolve(), args.source_ref)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(manifest, encoding="utf-8")


if __name__ == "__main__":
    main()
