/* Auto-generated by scripts/freeze_modules.py */

package com.oracle.graal.python.frozen;

import com.oracle.graal.python.frozen.abc.FrozenAbc1;
import com.oracle.graal.python.frozen.abc.FrozenAbc2;

public final class FrozenAbc {
    public static final byte[][] abcByteCode = {
                    FrozenAbc1.abcByteCode,
                    FrozenAbc2.abcByteCode,
    };
    public static final int abcByteCodeSize = FrozenAbc1.abcByteCodeSize + FrozenAbc2.abcByteCodeSize;
}