/*
 * Copyright (c) 2023, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * The Universal Permissive License (UPL), Version 1.0
 *
 * Subject to the condition set forth below, permission is hereby granted to any
 * person obtaining a copy of this software, associated documentation and/or
 * data (collectively the "Software"), free of charge and under any and all
 * copyright rights in the Software, and any and all patent rights owned or
 * freely licensable by each licensor hereunder covering either (i) the
 * unmodified Software as contributed to or provided by such licensor, or (ii)
 * the Larger Works (as defined below), to deal in both
 *
 * (a) the Software, and
 *
 * (b) any piece of software and/or hardware listed in the lrgrwrks.txt file if
 * one is included with the Software each a "Larger Work" to which the Software
 * is contributed by such licensors),
 *
 * without restriction, including without limitation the rights to copy, create
 * derivative works of, display, perform, and distribute the Software and make,
 * use, sell, offer for sale, import, export, have made, and have sold the
 * Software and the Larger Work(s), and to sublicense the foregoing rights on
 * either these or other terms.
 *
 * This license is subject to the following condition:
 *
 * The above copyright notice and either this complete permission notice or at a
 * minimum a reference to the UPL must be included in all copies or substantial
 * portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */


/*
   DO NOT EDIT THIS FILE!

   This file is automatically generated by hpy.tools.autogen.graalpy.autogen_ctx_init_jni_h
   See also hpy.tools.autogen and hpy/tools/public_api.h

   Run this to regenerate:
       make autogen

*/

_HPy_HIDDEN int init_autogen_jni_ctx(JNIEnv *env, jclass clazz, HPyContext *ctx, jlongArray jctx_handles);
_HPy_HIDDEN extern jmethodID jniMethod_ctx_Unicode_FromWideChar;
_HPy_HIDDEN HPy ctx_Unicode_FromWideChar_jni(HPyContext *ctx, const wchar_t *w, HPy_ssize_t size);
_HPy_HIDDEN extern jmethodID jniMethod_ctx_ListBuilder_New;
_HPy_HIDDEN HPyListBuilder ctx_ListBuilder_New_jni(HPyContext *ctx, HPy_ssize_t size);
_HPy_HIDDEN extern jmethodID jniMethod_ctx_ListBuilder_Set;
_HPy_HIDDEN void ctx_ListBuilder_Set_jni(HPyContext *ctx, HPyListBuilder builder, HPy_ssize_t index, HPy h_item);
_HPy_HIDDEN extern jmethodID jniMethod_ctx_ListBuilder_Build;
_HPy_HIDDEN HPy ctx_ListBuilder_Build_jni(HPyContext *ctx, HPyListBuilder builder);
_HPy_HIDDEN extern jmethodID jniMethod_ctx_ListBuilder_Cancel;
_HPy_HIDDEN void ctx_ListBuilder_Cancel_jni(HPyContext *ctx, HPyListBuilder builder);
_HPy_HIDDEN extern jmethodID jniMethod_ctx_TupleBuilder_New;
_HPy_HIDDEN HPyTupleBuilder ctx_TupleBuilder_New_jni(HPyContext *ctx, HPy_ssize_t size);
_HPy_HIDDEN extern jmethodID jniMethod_ctx_TupleBuilder_Set;
_HPy_HIDDEN void ctx_TupleBuilder_Set_jni(HPyContext *ctx, HPyTupleBuilder builder, HPy_ssize_t index, HPy h_item);
_HPy_HIDDEN extern jmethodID jniMethod_ctx_TupleBuilder_Build;
_HPy_HIDDEN HPy ctx_TupleBuilder_Build_jni(HPyContext *ctx, HPyTupleBuilder builder);
_HPy_HIDDEN extern jmethodID jniMethod_ctx_TupleBuilder_Cancel;
_HPy_HIDDEN void ctx_TupleBuilder_Cancel_jni(HPyContext *ctx, HPyTupleBuilder builder);
_HPy_HIDDEN extern jmethodID jniMethod_ctx_Global_Load;
_HPy_HIDDEN HPy ctx_Global_Load_jni(HPyContext *ctx, HPyGlobal global);

