/*
 * Copyright (c) 2023, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * The Universal Permissive License (UPL), Version 1.0
 *
 * Subject to the condition set forth below, permission is hereby granted to any
 * person obtaining a copy of this software, associated documentation and/or
 * data (collectively the "Software"), free of charge and under any and all
 * copyright rights in the Software, and any and all patent rights owned or
 * freely licensable by each licensor hereunder covering either (i) the
 * unmodified Software as contributed to or provided by such licensor, or (ii)
 * the Larger Works (as defined below), to deal in both
 *
 * (a) the Software, and
 *
 * (b) any piece of software and/or hardware listed in the lrgrwrks.txt file if
 * one is included with the Software each a "Larger Work" to which the Software
 * is contributed by such licensors),
 *
 * without restriction, including without limitation the rights to copy, create
 * derivative works of, display, perform, and distribute the Software and make,
 * use, sell, offer for sale, import, export, have made, and have sold the
 * Software and the Larger Work(s), and to sublicense the foregoing rights on
 * either these or other terms.
 *
 * This license is subject to the following condition:
 *
 * The above copyright notice and either this complete permission notice or at a
 * minimum a reference to the UPL must be included in all copies or substantial
 * portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */


/*
   DO NOT EDIT THIS FILE!

   This file is automatically generated by hpy.tools.autogen.graalpy.autogen_wrappers_jni
   See also hpy.tools.autogen and hpy/tools/public_api.h

   Run this to regenerate:
       make autogen

*/

#include "hpy_jni.h"
#include "hpynative.h"
#include "hpy_log.h"
#include "autogen_ctx_init_jni.h"

#define TRAMPOLINE(FUN_NAME) Java_GraalHPyJNIContext_ ## FUN_NAME

static jmethodID jniMethod_ctx_Module_Create;
static jmethodID jniMethod_ctx_Dup;
static jmethodID jniMethod_ctx_Close;
static jmethodID jniMethod_ctx_Long_FromLong;
static jmethodID jniMethod_ctx_Long_FromUnsignedLong;
static jmethodID jniMethod_ctx_Long_FromLongLong;
static jmethodID jniMethod_ctx_Long_FromUnsignedLongLong;
static jmethodID jniMethod_ctx_Long_FromSize_t;
static jmethodID jniMethod_ctx_Long_FromSsize_t;
static jmethodID jniMethod_ctx_Long_AsLong;
static jmethodID jniMethod_ctx_Long_AsUnsignedLong;
static jmethodID jniMethod_ctx_Long_AsUnsignedLongMask;
static jmethodID jniMethod_ctx_Long_AsLongLong;
static jmethodID jniMethod_ctx_Long_AsUnsignedLongLong;
static jmethodID jniMethod_ctx_Long_AsUnsignedLongLongMask;
static jmethodID jniMethod_ctx_Long_AsSize_t;
static jmethodID jniMethod_ctx_Long_AsSsize_t;
static jmethodID jniMethod_ctx_Long_AsVoidPtr;
static jmethodID jniMethod_ctx_Long_AsDouble;
static jmethodID jniMethod_ctx_Float_FromDouble;
static jmethodID jniMethod_ctx_Float_AsDouble;
static jmethodID jniMethod_ctx_Bool_FromLong;
static jmethodID jniMethod_ctx_Length;
static jmethodID jniMethod_ctx_Sequence_Check;
static jmethodID jniMethod_ctx_Number_Check;
static jmethodID jniMethod_ctx_Add;
static jmethodID jniMethod_ctx_Subtract;
static jmethodID jniMethod_ctx_Multiply;
static jmethodID jniMethod_ctx_MatrixMultiply;
static jmethodID jniMethod_ctx_FloorDivide;
static jmethodID jniMethod_ctx_TrueDivide;
static jmethodID jniMethod_ctx_Remainder;
static jmethodID jniMethod_ctx_Divmod;
static jmethodID jniMethod_ctx_Power;
static jmethodID jniMethod_ctx_Negative;
static jmethodID jniMethod_ctx_Positive;
static jmethodID jniMethod_ctx_Absolute;
static jmethodID jniMethod_ctx_Invert;
static jmethodID jniMethod_ctx_Lshift;
static jmethodID jniMethod_ctx_Rshift;
static jmethodID jniMethod_ctx_And;
static jmethodID jniMethod_ctx_Xor;
static jmethodID jniMethod_ctx_Or;
static jmethodID jniMethod_ctx_Index;
static jmethodID jniMethod_ctx_Long;
static jmethodID jniMethod_ctx_Float;
static jmethodID jniMethod_ctx_InPlaceAdd;
static jmethodID jniMethod_ctx_InPlaceSubtract;
static jmethodID jniMethod_ctx_InPlaceMultiply;
static jmethodID jniMethod_ctx_InPlaceMatrixMultiply;
static jmethodID jniMethod_ctx_InPlaceFloorDivide;
static jmethodID jniMethod_ctx_InPlaceTrueDivide;
static jmethodID jniMethod_ctx_InPlaceRemainder;
static jmethodID jniMethod_ctx_InPlacePower;
static jmethodID jniMethod_ctx_InPlaceLshift;
static jmethodID jniMethod_ctx_InPlaceRshift;
static jmethodID jniMethod_ctx_InPlaceAnd;
static jmethodID jniMethod_ctx_InPlaceXor;
static jmethodID jniMethod_ctx_InPlaceOr;
static jmethodID jniMethod_ctx_Callable_Check;
static jmethodID jniMethod_ctx_CallTupleDict;
static jmethodID jniMethod_ctx_FatalError;
static jmethodID jniMethod_ctx_Err_SetString;
static jmethodID jniMethod_ctx_Err_SetObject;
static jmethodID jniMethod_ctx_Err_SetFromErrnoWithFilename;
static jmethodID jniMethod_ctx_Err_SetFromErrnoWithFilenameObjects;
static jmethodID jniMethod_ctx_Err_Occurred;
static jmethodID jniMethod_ctx_Err_ExceptionMatches;
static jmethodID jniMethod_ctx_Err_NoMemory;
static jmethodID jniMethod_ctx_Err_Clear;
static jmethodID jniMethod_ctx_Err_NewException;
static jmethodID jniMethod_ctx_Err_NewExceptionWithDoc;
static jmethodID jniMethod_ctx_Err_WarnEx;
static jmethodID jniMethod_ctx_Err_WriteUnraisable;
static jmethodID jniMethod_ctx_IsTrue;
static jmethodID jniMethod_ctx_Type_FromSpec;
static jmethodID jniMethod_ctx_Type_GenericNew;
static jmethodID jniMethod_ctx_GetAttr;
static jmethodID jniMethod_ctx_GetAttr_s;
static jmethodID jniMethod_ctx_MaybeGetAttr_s;
static jmethodID jniMethod_ctx_HasAttr;
static jmethodID jniMethod_ctx_HasAttr_s;
static jmethodID jniMethod_ctx_SetAttr;
static jmethodID jniMethod_ctx_SetAttr_s;
static jmethodID jniMethod_ctx_GetItem;
static jmethodID jniMethod_ctx_GetItem_i;
static jmethodID jniMethod_ctx_GetItem_s;
static jmethodID jniMethod_ctx_Contains;
static jmethodID jniMethod_ctx_SetItem;
static jmethodID jniMethod_ctx_SetItem_i;
static jmethodID jniMethod_ctx_SetItem_s;
static jmethodID jniMethod_ctx_Type;
static jmethodID jniMethod_ctx_TypeCheck;
static jmethodID jniMethod_ctx_TypeCheck_g;
static jmethodID jniMethod_ctx_SetType;
static jmethodID jniMethod_ctx_Type_IsSubtype;
static jmethodID jniMethod_ctx_Type_GetName;
static jmethodID jniMethod_ctx_Is;
static jmethodID jniMethod_ctx_Is_g;
static jmethodID jniMethod_ctx_AsStruct;
static jmethodID jniMethod_ctx_AsStructLegacy;
static jmethodID jniMethod_ctx_New;
static jmethodID jniMethod_ctx_Repr;
static jmethodID jniMethod_ctx_Str;
static jmethodID jniMethod_ctx_ASCII;
static jmethodID jniMethod_ctx_Bytes;
static jmethodID jniMethod_ctx_RichCompare;
static jmethodID jniMethod_ctx_RichCompareBool;
static jmethodID jniMethod_ctx_Hash;
static jmethodID jniMethod_ctx_SeqIter_New;
static jmethodID jniMethod_ctx_Bytes_Check;
static jmethodID jniMethod_ctx_Bytes_Size;
static jmethodID jniMethod_ctx_Bytes_GET_SIZE;
static jmethodID jniMethod_ctx_Bytes_AsString;
static jmethodID jniMethod_ctx_Bytes_AS_STRING;
static jmethodID jniMethod_ctx_Bytes_FromString;
static jmethodID jniMethod_ctx_Bytes_FromStringAndSize;
static jmethodID jniMethod_ctx_Unicode_FromString;
static jmethodID jniMethod_ctx_Unicode_Check;
static jmethodID jniMethod_ctx_Unicode_AsASCIIString;
static jmethodID jniMethod_ctx_Unicode_AsLatin1String;
static jmethodID jniMethod_ctx_Unicode_AsUTF8String;
static jmethodID jniMethod_ctx_Unicode_AsUTF8AndSize;
static jmethodID jniMethod_ctx_Unicode_FromWideChar;
static jmethodID jniMethod_ctx_Unicode_DecodeFSDefault;
static jmethodID jniMethod_ctx_Unicode_DecodeFSDefaultAndSize;
static jmethodID jniMethod_ctx_Unicode_EncodeFSDefault;
static jmethodID jniMethod_ctx_Unicode_ReadChar;
static jmethodID jniMethod_ctx_Unicode_DecodeASCII;
static jmethodID jniMethod_ctx_Unicode_DecodeLatin1;
static jmethodID jniMethod_ctx_Unicode_FromEncodedObject;
static jmethodID jniMethod_ctx_Unicode_InternFromString;
static jmethodID jniMethod_ctx_Unicode_Substring;
static jmethodID jniMethod_ctx_List_Check;
static jmethodID jniMethod_ctx_List_New;
static jmethodID jniMethod_ctx_List_Append;
static jmethodID jniMethod_ctx_Dict_Check;
static jmethodID jniMethod_ctx_Dict_New;
static jmethodID jniMethod_ctx_Dict_Keys;
static jmethodID jniMethod_ctx_Dict_GetItem;
static jmethodID jniMethod_ctx_Tuple_Check;
static jmethodID jniMethod_ctx_Tuple_FromArray;
static jmethodID jniMethod_ctx_Slice_Unpack;
static jmethodID jniMethod_ctx_ContextVar_New;
static jmethodID jniMethod_ctx_ContextVar_Get;
static jmethodID jniMethod_ctx_ContextVar_Set;
static jmethodID jniMethod_ctx_Import_ImportModule;
static jmethodID jniMethod_ctx_Capsule_New;
static jmethodID jniMethod_ctx_Capsule_Get;
static jmethodID jniMethod_ctx_Capsule_IsValid;
static jmethodID jniMethod_ctx_Capsule_Set;
static jmethodID jniMethod_ctx_FromPyObject;
static jmethodID jniMethod_ctx_AsPyObject;
static jmethodID jniMethod_ctx_CallRealFunctionFromTrampoline;
static jmethodID jniMethod_ctx_ListBuilder_New;
static jmethodID jniMethod_ctx_ListBuilder_Set;
static jmethodID jniMethod_ctx_ListBuilder_Build;
static jmethodID jniMethod_ctx_ListBuilder_Cancel;
static jmethodID jniMethod_ctx_TupleBuilder_New;
static jmethodID jniMethod_ctx_TupleBuilder_Set;
static jmethodID jniMethod_ctx_TupleBuilder_Build;
static jmethodID jniMethod_ctx_TupleBuilder_Cancel;
static jmethodID jniMethod_ctx_Tracker_New;
static jmethodID jniMethod_ctx_Tracker_Add;
static jmethodID jniMethod_ctx_Tracker_ForgetAll;
static jmethodID jniMethod_ctx_Tracker_Close;
static jmethodID jniMethod_ctx_Field_Store;
static jmethodID jniMethod_ctx_Field_Load;
static jmethodID jniMethod_ctx_ReenterPythonExecution;
static jmethodID jniMethod_ctx_LeavePythonExecution;
static jmethodID jniMethod_ctx_Global_Store;
static jmethodID jniMethod_ctx_Global_Load;
static jmethodID jniMethod_ctx_Dump;
static jmethodID jniMethod_ctx_Type_CheckSlot;

_HPy_HIDDEN int init_autogen_jni_ctx(JNIEnv *env, jclass clazz, HPyContext *ctx)
{
    jniMethod_ctx_Module_Create = (*env)->GetMethodID(env, clazz, "ctxModuleCreate", "(J)J");
    if (jniMethod_ctx_Module_Create == NULL) {
        LOGS("ERROR: Java method ctxModuleCreate not found found !\n");
        return 1;
    }
    ctx->ctx_Module_Create = &ctx_Module_Create_jni;
    jniMethod_ctx_Dup = (*env)->GetMethodID(env, clazz, "ctxDup", "(J)J");
    if (jniMethod_ctx_Dup == NULL) {
        LOGS("ERROR: Java method ctxDup not found found !\n");
        return 1;
    }
    ctx->ctx_Dup = &ctx_Dup_jni;
    jniMethod_ctx_Close = (*env)->GetMethodID(env, clazz, "ctxClose", "(J)V");
    if (jniMethod_ctx_Close == NULL) {
        LOGS("ERROR: Java method ctxClose not found found !\n");
        return 1;
    }
    ctx->ctx_Close = &ctx_Close_jni;
    jniMethod_ctx_Long_FromLong = (*env)->GetMethodID(env, clazz, "ctxLongFromLong", "(L)J");
    if (jniMethod_ctx_Long_FromLong == NULL) {
        LOGS("ERROR: Java method ctxLongFromLong not found found !\n");
        return 1;
    }
    ctx->ctx_Long_FromLong = &ctx_Long_FromLong_jni;
    jniMethod_ctx_Long_FromUnsignedLong = (*env)->GetMethodID(env, clazz, "ctxLongFromUnsignedLong", "(J)J");
    if (jniMethod_ctx_Long_FromUnsignedLong == NULL) {
        LOGS("ERROR: Java method ctxLongFromUnsignedLong not found found !\n");
        return 1;
    }
    ctx->ctx_Long_FromUnsignedLong = &ctx_Long_FromUnsignedLong_jni;
    jniMethod_ctx_Long_FromLongLong = (*env)->GetMethodID(env, clazz, "ctxLongFromLongLong", "(J)J");
    if (jniMethod_ctx_Long_FromLongLong == NULL) {
        LOGS("ERROR: Java method ctxLongFromLongLong not found found !\n");
        return 1;
    }
    ctx->ctx_Long_FromLongLong = &ctx_Long_FromLongLong_jni;
    jniMethod_ctx_Long_FromUnsignedLongLong = (*env)->GetMethodID(env, clazz, "ctxLongFromUnsignedLongLong", "(J)J");
    if (jniMethod_ctx_Long_FromUnsignedLongLong == NULL) {
        LOGS("ERROR: Java method ctxLongFromUnsignedLongLong not found found !\n");
        return 1;
    }
    ctx->ctx_Long_FromUnsignedLongLong = &ctx_Long_FromUnsignedLongLong_jni;
    jniMethod_ctx_Long_FromSize_t = (*env)->GetMethodID(env, clazz, "ctxLongFromSizet", "(J)J");
    if (jniMethod_ctx_Long_FromSize_t == NULL) {
        LOGS("ERROR: Java method ctxLongFromSizet not found found !\n");
        return 1;
    }
    ctx->ctx_Long_FromSize_t = &ctx_Long_FromSize_t_jni;
    jniMethod_ctx_Long_FromSsize_t = (*env)->GetMethodID(env, clazz, "ctxLongFromSsizet", "(J)J");
    if (jniMethod_ctx_Long_FromSsize_t == NULL) {
        LOGS("ERROR: Java method ctxLongFromSsizet not found found !\n");
        return 1;
    }
    ctx->ctx_Long_FromSsize_t = &ctx_Long_FromSsize_t_jni;
    jniMethod_ctx_Long_AsLong = (*env)->GetMethodID(env, clazz, "ctxLongAsLong", "(J)L");
    if (jniMethod_ctx_Long_AsLong == NULL) {
        LOGS("ERROR: Java method ctxLongAsLong not found found !\n");
        return 1;
    }
    ctx->ctx_Long_AsLong = &ctx_Long_AsLong_jni;
    jniMethod_ctx_Long_AsUnsignedLong = (*env)->GetMethodID(env, clazz, "ctxLongAsUnsignedLong", "(J)J");
    if (jniMethod_ctx_Long_AsUnsignedLong == NULL) {
        LOGS("ERROR: Java method ctxLongAsUnsignedLong not found found !\n");
        return 1;
    }
    ctx->ctx_Long_AsUnsignedLong = &ctx_Long_AsUnsignedLong_jni;
    jniMethod_ctx_Long_AsUnsignedLongMask = (*env)->GetMethodID(env, clazz, "ctxLongAsUnsignedLongMask", "(J)J");
    if (jniMethod_ctx_Long_AsUnsignedLongMask == NULL) {
        LOGS("ERROR: Java method ctxLongAsUnsignedLongMask not found found !\n");
        return 1;
    }
    ctx->ctx_Long_AsUnsignedLongMask = &ctx_Long_AsUnsignedLongMask_jni;
    jniMethod_ctx_Long_AsLongLong = (*env)->GetMethodID(env, clazz, "ctxLongAsLongLong", "(J)J");
    if (jniMethod_ctx_Long_AsLongLong == NULL) {
        LOGS("ERROR: Java method ctxLongAsLongLong not found found !\n");
        return 1;
    }
    ctx->ctx_Long_AsLongLong = &ctx_Long_AsLongLong_jni;
    jniMethod_ctx_Long_AsUnsignedLongLong = (*env)->GetMethodID(env, clazz, "ctxLongAsUnsignedLongLong", "(J)J");
    if (jniMethod_ctx_Long_AsUnsignedLongLong == NULL) {
        LOGS("ERROR: Java method ctxLongAsUnsignedLongLong not found found !\n");
        return 1;
    }
    ctx->ctx_Long_AsUnsignedLongLong = &ctx_Long_AsUnsignedLongLong_jni;
    jniMethod_ctx_Long_AsUnsignedLongLongMask = (*env)->GetMethodID(env, clazz, "ctxLongAsUnsignedLongLongMask", "(J)J");
    if (jniMethod_ctx_Long_AsUnsignedLongLongMask == NULL) {
        LOGS("ERROR: Java method ctxLongAsUnsignedLongLongMask not found found !\n");
        return 1;
    }
    ctx->ctx_Long_AsUnsignedLongLongMask = &ctx_Long_AsUnsignedLongLongMask_jni;
    jniMethod_ctx_Long_AsSize_t = (*env)->GetMethodID(env, clazz, "ctxLongAsSizet", "(J)J");
    if (jniMethod_ctx_Long_AsSize_t == NULL) {
        LOGS("ERROR: Java method ctxLongAsSizet not found found !\n");
        return 1;
    }
    ctx->ctx_Long_AsSize_t = &ctx_Long_AsSize_t_jni;
    jniMethod_ctx_Long_AsSsize_t = (*env)->GetMethodID(env, clazz, "ctxLongAsSsizet", "(J)J");
    if (jniMethod_ctx_Long_AsSsize_t == NULL) {
        LOGS("ERROR: Java method ctxLongAsSsizet not found found !\n");
        return 1;
    }
    ctx->ctx_Long_AsSsize_t = &ctx_Long_AsSsize_t_jni;
    jniMethod_ctx_Long_AsVoidPtr = (*env)->GetMethodID(env, clazz, "ctxLongAsVoidPtr", "(J)J");
    if (jniMethod_ctx_Long_AsVoidPtr == NULL) {
        LOGS("ERROR: Java method ctxLongAsVoidPtr not found found !\n");
        return 1;
    }
    ctx->ctx_Long_AsVoidPtr = &ctx_Long_AsVoidPtr_jni;
    jniMethod_ctx_Long_AsDouble = (*env)->GetMethodID(env, clazz, "ctxLongAsDouble", "(J)D");
    if (jniMethod_ctx_Long_AsDouble == NULL) {
        LOGS("ERROR: Java method ctxLongAsDouble not found found !\n");
        return 1;
    }
    ctx->ctx_Long_AsDouble = &ctx_Long_AsDouble_jni;
    jniMethod_ctx_Float_FromDouble = (*env)->GetMethodID(env, clazz, "ctxFloatFromDouble", "(D)J");
    if (jniMethod_ctx_Float_FromDouble == NULL) {
        LOGS("ERROR: Java method ctxFloatFromDouble not found found !\n");
        return 1;
    }
    ctx->ctx_Float_FromDouble = &ctx_Float_FromDouble_jni;
    jniMethod_ctx_Float_AsDouble = (*env)->GetMethodID(env, clazz, "ctxFloatAsDouble", "(J)D");
    if (jniMethod_ctx_Float_AsDouble == NULL) {
        LOGS("ERROR: Java method ctxFloatAsDouble not found found !\n");
        return 1;
    }
    ctx->ctx_Float_AsDouble = &ctx_Float_AsDouble_jni;
    jniMethod_ctx_Bool_FromLong = (*env)->GetMethodID(env, clazz, "ctxBoolFromLong", "(L)J");
    if (jniMethod_ctx_Bool_FromLong == NULL) {
        LOGS("ERROR: Java method ctxBoolFromLong not found found !\n");
        return 1;
    }
    ctx->ctx_Bool_FromLong = &ctx_Bool_FromLong_jni;
    jniMethod_ctx_Length = (*env)->GetMethodID(env, clazz, "ctxLength", "(J)J");
    if (jniMethod_ctx_Length == NULL) {
        LOGS("ERROR: Java method ctxLength not found found !\n");
        return 1;
    }
    ctx->ctx_Length = &ctx_Length_jni;
    jniMethod_ctx_Sequence_Check = (*env)->GetMethodID(env, clazz, "ctxSequenceCheck", "(J)I");
    if (jniMethod_ctx_Sequence_Check == NULL) {
        LOGS("ERROR: Java method ctxSequenceCheck not found found !\n");
        return 1;
    }
    ctx->ctx_Sequence_Check = &ctx_Sequence_Check_jni;
    jniMethod_ctx_Number_Check = (*env)->GetMethodID(env, clazz, "ctxNumberCheck", "(J)I");
    if (jniMethod_ctx_Number_Check == NULL) {
        LOGS("ERROR: Java method ctxNumberCheck not found found !\n");
        return 1;
    }
    ctx->ctx_Number_Check = &ctx_Number_Check_jni;
    jniMethod_ctx_Add = (*env)->GetMethodID(env, clazz, "ctxAdd", "(JJ)J");
    if (jniMethod_ctx_Add == NULL) {
        LOGS("ERROR: Java method ctxAdd not found found !\n");
        return 1;
    }
    ctx->ctx_Add = &ctx_Add_jni;
    jniMethod_ctx_Subtract = (*env)->GetMethodID(env, clazz, "ctxSubtract", "(JJ)J");
    if (jniMethod_ctx_Subtract == NULL) {
        LOGS("ERROR: Java method ctxSubtract not found found !\n");
        return 1;
    }
    ctx->ctx_Subtract = &ctx_Subtract_jni;
    jniMethod_ctx_Multiply = (*env)->GetMethodID(env, clazz, "ctxMultiply", "(JJ)J");
    if (jniMethod_ctx_Multiply == NULL) {
        LOGS("ERROR: Java method ctxMultiply not found found !\n");
        return 1;
    }
    ctx->ctx_Multiply = &ctx_Multiply_jni;
    jniMethod_ctx_MatrixMultiply = (*env)->GetMethodID(env, clazz, "ctxMatrixMultiply", "(JJ)J");
    if (jniMethod_ctx_MatrixMultiply == NULL) {
        LOGS("ERROR: Java method ctxMatrixMultiply not found found !\n");
        return 1;
    }
    ctx->ctx_MatrixMultiply = &ctx_MatrixMultiply_jni;
    jniMethod_ctx_FloorDivide = (*env)->GetMethodID(env, clazz, "ctxFloorDivide", "(JJ)J");
    if (jniMethod_ctx_FloorDivide == NULL) {
        LOGS("ERROR: Java method ctxFloorDivide not found found !\n");
        return 1;
    }
    ctx->ctx_FloorDivide = &ctx_FloorDivide_jni;
    jniMethod_ctx_TrueDivide = (*env)->GetMethodID(env, clazz, "ctxTrueDivide", "(JJ)J");
    if (jniMethod_ctx_TrueDivide == NULL) {
        LOGS("ERROR: Java method ctxTrueDivide not found found !\n");
        return 1;
    }
    ctx->ctx_TrueDivide = &ctx_TrueDivide_jni;
    jniMethod_ctx_Remainder = (*env)->GetMethodID(env, clazz, "ctxRemainder", "(JJ)J");
    if (jniMethod_ctx_Remainder == NULL) {
        LOGS("ERROR: Java method ctxRemainder not found found !\n");
        return 1;
    }
    ctx->ctx_Remainder = &ctx_Remainder_jni;
    jniMethod_ctx_Divmod = (*env)->GetMethodID(env, clazz, "ctxDivmod", "(JJ)J");
    if (jniMethod_ctx_Divmod == NULL) {
        LOGS("ERROR: Java method ctxDivmod not found found !\n");
        return 1;
    }
    ctx->ctx_Divmod = &ctx_Divmod_jni;
    jniMethod_ctx_Power = (*env)->GetMethodID(env, clazz, "ctxPower", "(JJJ)J");
    if (jniMethod_ctx_Power == NULL) {
        LOGS("ERROR: Java method ctxPower not found found !\n");
        return 1;
    }
    ctx->ctx_Power = &ctx_Power_jni;
    jniMethod_ctx_Negative = (*env)->GetMethodID(env, clazz, "ctxNegative", "(J)J");
    if (jniMethod_ctx_Negative == NULL) {
        LOGS("ERROR: Java method ctxNegative not found found !\n");
        return 1;
    }
    ctx->ctx_Negative = &ctx_Negative_jni;
    jniMethod_ctx_Positive = (*env)->GetMethodID(env, clazz, "ctxPositive", "(J)J");
    if (jniMethod_ctx_Positive == NULL) {
        LOGS("ERROR: Java method ctxPositive not found found !\n");
        return 1;
    }
    ctx->ctx_Positive = &ctx_Positive_jni;
    jniMethod_ctx_Absolute = (*env)->GetMethodID(env, clazz, "ctxAbsolute", "(J)J");
    if (jniMethod_ctx_Absolute == NULL) {
        LOGS("ERROR: Java method ctxAbsolute not found found !\n");
        return 1;
    }
    ctx->ctx_Absolute = &ctx_Absolute_jni;
    jniMethod_ctx_Invert = (*env)->GetMethodID(env, clazz, "ctxInvert", "(J)J");
    if (jniMethod_ctx_Invert == NULL) {
        LOGS("ERROR: Java method ctxInvert not found found !\n");
        return 1;
    }
    ctx->ctx_Invert = &ctx_Invert_jni;
    jniMethod_ctx_Lshift = (*env)->GetMethodID(env, clazz, "ctxLshift", "(JJ)J");
    if (jniMethod_ctx_Lshift == NULL) {
        LOGS("ERROR: Java method ctxLshift not found found !\n");
        return 1;
    }
    ctx->ctx_Lshift = &ctx_Lshift_jni;
    jniMethod_ctx_Rshift = (*env)->GetMethodID(env, clazz, "ctxRshift", "(JJ)J");
    if (jniMethod_ctx_Rshift == NULL) {
        LOGS("ERROR: Java method ctxRshift not found found !\n");
        return 1;
    }
    ctx->ctx_Rshift = &ctx_Rshift_jni;
    jniMethod_ctx_And = (*env)->GetMethodID(env, clazz, "ctxAnd", "(JJ)J");
    if (jniMethod_ctx_And == NULL) {
        LOGS("ERROR: Java method ctxAnd not found found !\n");
        return 1;
    }
    ctx->ctx_And = &ctx_And_jni;
    jniMethod_ctx_Xor = (*env)->GetMethodID(env, clazz, "ctxXor", "(JJ)J");
    if (jniMethod_ctx_Xor == NULL) {
        LOGS("ERROR: Java method ctxXor not found found !\n");
        return 1;
    }
    ctx->ctx_Xor = &ctx_Xor_jni;
    jniMethod_ctx_Or = (*env)->GetMethodID(env, clazz, "ctxOr", "(JJ)J");
    if (jniMethod_ctx_Or == NULL) {
        LOGS("ERROR: Java method ctxOr not found found !\n");
        return 1;
    }
    ctx->ctx_Or = &ctx_Or_jni;
    jniMethod_ctx_Index = (*env)->GetMethodID(env, clazz, "ctxIndex", "(J)J");
    if (jniMethod_ctx_Index == NULL) {
        LOGS("ERROR: Java method ctxIndex not found found !\n");
        return 1;
    }
    ctx->ctx_Index = &ctx_Index_jni;
    jniMethod_ctx_Long = (*env)->GetMethodID(env, clazz, "ctxLong", "(J)J");
    if (jniMethod_ctx_Long == NULL) {
        LOGS("ERROR: Java method ctxLong not found found !\n");
        return 1;
    }
    ctx->ctx_Long = &ctx_Long_jni;
    jniMethod_ctx_Float = (*env)->GetMethodID(env, clazz, "ctxFloat", "(J)J");
    if (jniMethod_ctx_Float == NULL) {
        LOGS("ERROR: Java method ctxFloat not found found !\n");
        return 1;
    }
    ctx->ctx_Float = &ctx_Float_jni;
    jniMethod_ctx_InPlaceAdd = (*env)->GetMethodID(env, clazz, "ctxInPlaceAdd", "(JJ)J");
    if (jniMethod_ctx_InPlaceAdd == NULL) {
        LOGS("ERROR: Java method ctxInPlaceAdd not found found !\n");
        return 1;
    }
    ctx->ctx_InPlaceAdd = &ctx_InPlaceAdd_jni;
    jniMethod_ctx_InPlaceSubtract = (*env)->GetMethodID(env, clazz, "ctxInPlaceSubtract", "(JJ)J");
    if (jniMethod_ctx_InPlaceSubtract == NULL) {
        LOGS("ERROR: Java method ctxInPlaceSubtract not found found !\n");
        return 1;
    }
    ctx->ctx_InPlaceSubtract = &ctx_InPlaceSubtract_jni;
    jniMethod_ctx_InPlaceMultiply = (*env)->GetMethodID(env, clazz, "ctxInPlaceMultiply", "(JJ)J");
    if (jniMethod_ctx_InPlaceMultiply == NULL) {
        LOGS("ERROR: Java method ctxInPlaceMultiply not found found !\n");
        return 1;
    }
    ctx->ctx_InPlaceMultiply = &ctx_InPlaceMultiply_jni;
    jniMethod_ctx_InPlaceMatrixMultiply = (*env)->GetMethodID(env, clazz, "ctxInPlaceMatrixMultiply", "(JJ)J");
    if (jniMethod_ctx_InPlaceMatrixMultiply == NULL) {
        LOGS("ERROR: Java method ctxInPlaceMatrixMultiply not found found !\n");
        return 1;
    }
    ctx->ctx_InPlaceMatrixMultiply = &ctx_InPlaceMatrixMultiply_jni;
    jniMethod_ctx_InPlaceFloorDivide = (*env)->GetMethodID(env, clazz, "ctxInPlaceFloorDivide", "(JJ)J");
    if (jniMethod_ctx_InPlaceFloorDivide == NULL) {
        LOGS("ERROR: Java method ctxInPlaceFloorDivide not found found !\n");
        return 1;
    }
    ctx->ctx_InPlaceFloorDivide = &ctx_InPlaceFloorDivide_jni;
    jniMethod_ctx_InPlaceTrueDivide = (*env)->GetMethodID(env, clazz, "ctxInPlaceTrueDivide", "(JJ)J");
    if (jniMethod_ctx_InPlaceTrueDivide == NULL) {
        LOGS("ERROR: Java method ctxInPlaceTrueDivide not found found !\n");
        return 1;
    }
    ctx->ctx_InPlaceTrueDivide = &ctx_InPlaceTrueDivide_jni;
    jniMethod_ctx_InPlaceRemainder = (*env)->GetMethodID(env, clazz, "ctxInPlaceRemainder", "(JJ)J");
    if (jniMethod_ctx_InPlaceRemainder == NULL) {
        LOGS("ERROR: Java method ctxInPlaceRemainder not found found !\n");
        return 1;
    }
    ctx->ctx_InPlaceRemainder = &ctx_InPlaceRemainder_jni;
    jniMethod_ctx_InPlacePower = (*env)->GetMethodID(env, clazz, "ctxInPlacePower", "(JJJ)J");
    if (jniMethod_ctx_InPlacePower == NULL) {
        LOGS("ERROR: Java method ctxInPlacePower not found found !\n");
        return 1;
    }
    ctx->ctx_InPlacePower = &ctx_InPlacePower_jni;
    jniMethod_ctx_InPlaceLshift = (*env)->GetMethodID(env, clazz, "ctxInPlaceLshift", "(JJ)J");
    if (jniMethod_ctx_InPlaceLshift == NULL) {
        LOGS("ERROR: Java method ctxInPlaceLshift not found found !\n");
        return 1;
    }
    ctx->ctx_InPlaceLshift = &ctx_InPlaceLshift_jni;
    jniMethod_ctx_InPlaceRshift = (*env)->GetMethodID(env, clazz, "ctxInPlaceRshift", "(JJ)J");
    if (jniMethod_ctx_InPlaceRshift == NULL) {
        LOGS("ERROR: Java method ctxInPlaceRshift not found found !\n");
        return 1;
    }
    ctx->ctx_InPlaceRshift = &ctx_InPlaceRshift_jni;
    jniMethod_ctx_InPlaceAnd = (*env)->GetMethodID(env, clazz, "ctxInPlaceAnd", "(JJ)J");
    if (jniMethod_ctx_InPlaceAnd == NULL) {
        LOGS("ERROR: Java method ctxInPlaceAnd not found found !\n");
        return 1;
    }
    ctx->ctx_InPlaceAnd = &ctx_InPlaceAnd_jni;
    jniMethod_ctx_InPlaceXor = (*env)->GetMethodID(env, clazz, "ctxInPlaceXor", "(JJ)J");
    if (jniMethod_ctx_InPlaceXor == NULL) {
        LOGS("ERROR: Java method ctxInPlaceXor not found found !\n");
        return 1;
    }
    ctx->ctx_InPlaceXor = &ctx_InPlaceXor_jni;
    jniMethod_ctx_InPlaceOr = (*env)->GetMethodID(env, clazz, "ctxInPlaceOr", "(JJ)J");
    if (jniMethod_ctx_InPlaceOr == NULL) {
        LOGS("ERROR: Java method ctxInPlaceOr not found found !\n");
        return 1;
    }
    ctx->ctx_InPlaceOr = &ctx_InPlaceOr_jni;
    jniMethod_ctx_Callable_Check = (*env)->GetMethodID(env, clazz, "ctxCallableCheck", "(J)I");
    if (jniMethod_ctx_Callable_Check == NULL) {
        LOGS("ERROR: Java method ctxCallableCheck not found found !\n");
        return 1;
    }
    ctx->ctx_Callable_Check = &ctx_Callable_Check_jni;
    jniMethod_ctx_CallTupleDict = (*env)->GetMethodID(env, clazz, "ctxCallTupleDict", "(JJJ)J");
    if (jniMethod_ctx_CallTupleDict == NULL) {
        LOGS("ERROR: Java method ctxCallTupleDict not found found !\n");
        return 1;
    }
    ctx->ctx_CallTupleDict = &ctx_CallTupleDict_jni;
    jniMethod_ctx_FatalError = (*env)->GetMethodID(env, clazz, "ctxFatalError", "(J)V");
    if (jniMethod_ctx_FatalError == NULL) {
        LOGS("ERROR: Java method ctxFatalError not found found !\n");
        return 1;
    }
    ctx->ctx_FatalError = &ctx_FatalError_jni;
    jniMethod_ctx_Err_SetString = (*env)->GetMethodID(env, clazz, "ctxErrSetString", "(JJ)V");
    if (jniMethod_ctx_Err_SetString == NULL) {
        LOGS("ERROR: Java method ctxErrSetString not found found !\n");
        return 1;
    }
    ctx->ctx_Err_SetString = &ctx_Err_SetString_jni;
    jniMethod_ctx_Err_SetObject = (*env)->GetMethodID(env, clazz, "ctxErrSetObject", "(JJ)V");
    if (jniMethod_ctx_Err_SetObject == NULL) {
        LOGS("ERROR: Java method ctxErrSetObject not found found !\n");
        return 1;
    }
    ctx->ctx_Err_SetObject = &ctx_Err_SetObject_jni;
    jniMethod_ctx_Err_SetFromErrnoWithFilename = (*env)->GetMethodID(env, clazz, "ctxErrSetFromErrnoWithFilename", "(JJ)J");
    if (jniMethod_ctx_Err_SetFromErrnoWithFilename == NULL) {
        LOGS("ERROR: Java method ctxErrSetFromErrnoWithFilename not found found !\n");
        return 1;
    }
    ctx->ctx_Err_SetFromErrnoWithFilename = &ctx_Err_SetFromErrnoWithFilename_jni;
    jniMethod_ctx_Err_SetFromErrnoWithFilenameObjects = (*env)->GetMethodID(env, clazz, "ctxErrSetFromErrnoWithFilenameObjects", "(JJJ)V");
    if (jniMethod_ctx_Err_SetFromErrnoWithFilenameObjects == NULL) {
        LOGS("ERROR: Java method ctxErrSetFromErrnoWithFilenameObjects not found found !\n");
        return 1;
    }
    ctx->ctx_Err_SetFromErrnoWithFilenameObjects = &ctx_Err_SetFromErrnoWithFilenameObjects_jni;
    jniMethod_ctx_Err_Occurred = (*env)->GetMethodID(env, clazz, "ctxErrOccurred", "()I");
    if (jniMethod_ctx_Err_Occurred == NULL) {
        LOGS("ERROR: Java method ctxErrOccurred not found found !\n");
        return 1;
    }
    ctx->ctx_Err_Occurred = &ctx_Err_Occurred_jni;
    jniMethod_ctx_Err_ExceptionMatches = (*env)->GetMethodID(env, clazz, "ctxErrExceptionMatches", "(J)I");
    if (jniMethod_ctx_Err_ExceptionMatches == NULL) {
        LOGS("ERROR: Java method ctxErrExceptionMatches not found found !\n");
        return 1;
    }
    ctx->ctx_Err_ExceptionMatches = &ctx_Err_ExceptionMatches_jni;
    jniMethod_ctx_Err_NoMemory = (*env)->GetMethodID(env, clazz, "ctxErrNoMemory", "()V");
    if (jniMethod_ctx_Err_NoMemory == NULL) {
        LOGS("ERROR: Java method ctxErrNoMemory not found found !\n");
        return 1;
    }
    ctx->ctx_Err_NoMemory = &ctx_Err_NoMemory_jni;
    jniMethod_ctx_Err_Clear = (*env)->GetMethodID(env, clazz, "ctxErrClear", "()V");
    if (jniMethod_ctx_Err_Clear == NULL) {
        LOGS("ERROR: Java method ctxErrClear not found found !\n");
        return 1;
    }
    ctx->ctx_Err_Clear = &ctx_Err_Clear_jni;
    jniMethod_ctx_Err_NewException = (*env)->GetMethodID(env, clazz, "ctxErrNewException", "(JJJ)J");
    if (jniMethod_ctx_Err_NewException == NULL) {
        LOGS("ERROR: Java method ctxErrNewException not found found !\n");
        return 1;
    }
    ctx->ctx_Err_NewException = &ctx_Err_NewException_jni;
    jniMethod_ctx_Err_NewExceptionWithDoc = (*env)->GetMethodID(env, clazz, "ctxErrNewExceptionWithDoc", "(JJJJ)J");
    if (jniMethod_ctx_Err_NewExceptionWithDoc == NULL) {
        LOGS("ERROR: Java method ctxErrNewExceptionWithDoc not found found !\n");
        return 1;
    }
    ctx->ctx_Err_NewExceptionWithDoc = &ctx_Err_NewExceptionWithDoc_jni;
    jniMethod_ctx_Err_WarnEx = (*env)->GetMethodID(env, clazz, "ctxErrWarnEx", "(JJJ)I");
    if (jniMethod_ctx_Err_WarnEx == NULL) {
        LOGS("ERROR: Java method ctxErrWarnEx not found found !\n");
        return 1;
    }
    ctx->ctx_Err_WarnEx = &ctx_Err_WarnEx_jni;
    jniMethod_ctx_Err_WriteUnraisable = (*env)->GetMethodID(env, clazz, "ctxErrWriteUnraisable", "(J)V");
    if (jniMethod_ctx_Err_WriteUnraisable == NULL) {
        LOGS("ERROR: Java method ctxErrWriteUnraisable not found found !\n");
        return 1;
    }
    ctx->ctx_Err_WriteUnraisable = &ctx_Err_WriteUnraisable_jni;
    jniMethod_ctx_IsTrue = (*env)->GetMethodID(env, clazz, "ctxIsTrue", "(J)I");
    if (jniMethod_ctx_IsTrue == NULL) {
        LOGS("ERROR: Java method ctxIsTrue not found found !\n");
        return 1;
    }
    ctx->ctx_IsTrue = &ctx_IsTrue_jni;
    jniMethod_ctx_Type_FromSpec = (*env)->GetMethodID(env, clazz, "ctxTypeFromSpec", "(JJ)J");
    if (jniMethod_ctx_Type_FromSpec == NULL) {
        LOGS("ERROR: Java method ctxTypeFromSpec not found found !\n");
        return 1;
    }
    ctx->ctx_Type_FromSpec = &ctx_Type_FromSpec_jni;
    jniMethod_ctx_Type_GenericNew = (*env)->GetMethodID(env, clazz, "ctxTypeGenericNew", "(JJJJ)J");
    if (jniMethod_ctx_Type_GenericNew == NULL) {
        LOGS("ERROR: Java method ctxTypeGenericNew not found found !\n");
        return 1;
    }
    ctx->ctx_Type_GenericNew = &ctx_Type_GenericNew_jni;
    jniMethod_ctx_GetAttr = (*env)->GetMethodID(env, clazz, "ctxGetAttr", "(JJ)J");
    if (jniMethod_ctx_GetAttr == NULL) {
        LOGS("ERROR: Java method ctxGetAttr not found found !\n");
        return 1;
    }
    ctx->ctx_GetAttr = &ctx_GetAttr_jni;
    jniMethod_ctx_GetAttr_s = (*env)->GetMethodID(env, clazz, "ctxGetAttrs", "(JJ)J");
    if (jniMethod_ctx_GetAttr_s == NULL) {
        LOGS("ERROR: Java method ctxGetAttrs not found found !\n");
        return 1;
    }
    ctx->ctx_GetAttr_s = &ctx_GetAttr_s_jni;
    jniMethod_ctx_MaybeGetAttr_s = (*env)->GetMethodID(env, clazz, "ctxMaybeGetAttrs", "(JJ)J");
    if (jniMethod_ctx_MaybeGetAttr_s == NULL) {
        LOGS("ERROR: Java method ctxMaybeGetAttrs not found found !\n");
        return 1;
    }
    ctx->ctx_MaybeGetAttr_s = &ctx_MaybeGetAttr_s_jni;
    jniMethod_ctx_HasAttr = (*env)->GetMethodID(env, clazz, "ctxHasAttr", "(JJ)I");
    if (jniMethod_ctx_HasAttr == NULL) {
        LOGS("ERROR: Java method ctxHasAttr not found found !\n");
        return 1;
    }
    ctx->ctx_HasAttr = &ctx_HasAttr_jni;
    jniMethod_ctx_HasAttr_s = (*env)->GetMethodID(env, clazz, "ctxHasAttrs", "(JJ)I");
    if (jniMethod_ctx_HasAttr_s == NULL) {
        LOGS("ERROR: Java method ctxHasAttrs not found found !\n");
        return 1;
    }
    ctx->ctx_HasAttr_s = &ctx_HasAttr_s_jni;
    jniMethod_ctx_SetAttr = (*env)->GetMethodID(env, clazz, "ctxSetAttr", "(JJJ)I");
    if (jniMethod_ctx_SetAttr == NULL) {
        LOGS("ERROR: Java method ctxSetAttr not found found !\n");
        return 1;
    }
    ctx->ctx_SetAttr = &ctx_SetAttr_jni;
    jniMethod_ctx_SetAttr_s = (*env)->GetMethodID(env, clazz, "ctxSetAttrs", "(JJJ)I");
    if (jniMethod_ctx_SetAttr_s == NULL) {
        LOGS("ERROR: Java method ctxSetAttrs not found found !\n");
        return 1;
    }
    ctx->ctx_SetAttr_s = &ctx_SetAttr_s_jni;
    jniMethod_ctx_GetItem = (*env)->GetMethodID(env, clazz, "ctxGetItem", "(JJ)J");
    if (jniMethod_ctx_GetItem == NULL) {
        LOGS("ERROR: Java method ctxGetItem not found found !\n");
        return 1;
    }
    ctx->ctx_GetItem = &ctx_GetItem_jni;
    jniMethod_ctx_GetItem_i = (*env)->GetMethodID(env, clazz, "ctxGetItemi", "(JJ)J");
    if (jniMethod_ctx_GetItem_i == NULL) {
        LOGS("ERROR: Java method ctxGetItemi not found found !\n");
        return 1;
    }
    ctx->ctx_GetItem_i = &ctx_GetItem_i_jni;
    jniMethod_ctx_GetItem_s = (*env)->GetMethodID(env, clazz, "ctxGetItems", "(JJ)J");
    if (jniMethod_ctx_GetItem_s == NULL) {
        LOGS("ERROR: Java method ctxGetItems not found found !\n");
        return 1;
    }
    ctx->ctx_GetItem_s = &ctx_GetItem_s_jni;
    jniMethod_ctx_Contains = (*env)->GetMethodID(env, clazz, "ctxContains", "(JJ)I");
    if (jniMethod_ctx_Contains == NULL) {
        LOGS("ERROR: Java method ctxContains not found found !\n");
        return 1;
    }
    ctx->ctx_Contains = &ctx_Contains_jni;
    jniMethod_ctx_SetItem = (*env)->GetMethodID(env, clazz, "ctxSetItem", "(JJJ)I");
    if (jniMethod_ctx_SetItem == NULL) {
        LOGS("ERROR: Java method ctxSetItem not found found !\n");
        return 1;
    }
    ctx->ctx_SetItem = &ctx_SetItem_jni;
    jniMethod_ctx_SetItem_i = (*env)->GetMethodID(env, clazz, "ctxSetItemi", "(JJJ)I");
    if (jniMethod_ctx_SetItem_i == NULL) {
        LOGS("ERROR: Java method ctxSetItemi not found found !\n");
        return 1;
    }
    ctx->ctx_SetItem_i = &ctx_SetItem_i_jni;
    jniMethod_ctx_SetItem_s = (*env)->GetMethodID(env, clazz, "ctxSetItems", "(JJJ)I");
    if (jniMethod_ctx_SetItem_s == NULL) {
        LOGS("ERROR: Java method ctxSetItems not found found !\n");
        return 1;
    }
    ctx->ctx_SetItem_s = &ctx_SetItem_s_jni;
    jniMethod_ctx_Type = (*env)->GetMethodID(env, clazz, "ctxType", "(J)J");
    if (jniMethod_ctx_Type == NULL) {
        LOGS("ERROR: Java method ctxType not found found !\n");
        return 1;
    }
    ctx->ctx_Type = &ctx_Type_jni;
    jniMethod_ctx_TypeCheck = (*env)->GetMethodID(env, clazz, "ctxTypeCheck", "(JJ)I");
    if (jniMethod_ctx_TypeCheck == NULL) {
        LOGS("ERROR: Java method ctxTypeCheck not found found !\n");
        return 1;
    }
    ctx->ctx_TypeCheck = &ctx_TypeCheck_jni;
    jniMethod_ctx_TypeCheck_g = (*env)->GetMethodID(env, clazz, "ctxTypeCheckg", "(JJ)I");
    if (jniMethod_ctx_TypeCheck_g == NULL) {
        LOGS("ERROR: Java method ctxTypeCheckg not found found !\n");
        return 1;
    }
    ctx->ctx_TypeCheck_g = &ctx_TypeCheck_g_jni;
    jniMethod_ctx_SetType = (*env)->GetMethodID(env, clazz, "ctxSetType", "(JJ)I");
    if (jniMethod_ctx_SetType == NULL) {
        LOGS("ERROR: Java method ctxSetType not found found !\n");
        return 1;
    }
    ctx->ctx_SetType = &ctx_SetType_jni;
    jniMethod_ctx_Type_IsSubtype = (*env)->GetMethodID(env, clazz, "ctxTypeIsSubtype", "(JJ)I");
    if (jniMethod_ctx_Type_IsSubtype == NULL) {
        LOGS("ERROR: Java method ctxTypeIsSubtype not found found !\n");
        return 1;
    }
    ctx->ctx_Type_IsSubtype = &ctx_Type_IsSubtype_jni;
    jniMethod_ctx_Type_GetName = (*env)->GetMethodID(env, clazz, "ctxTypeGetName", "(J)J");
    if (jniMethod_ctx_Type_GetName == NULL) {
        LOGS("ERROR: Java method ctxTypeGetName not found found !\n");
        return 1;
    }
    ctx->ctx_Type_GetName = &ctx_Type_GetName_jni;
    jniMethod_ctx_Is = (*env)->GetMethodID(env, clazz, "ctxIs", "(JJ)I");
    if (jniMethod_ctx_Is == NULL) {
        LOGS("ERROR: Java method ctxIs not found found !\n");
        return 1;
    }
    ctx->ctx_Is = &ctx_Is_jni;
    jniMethod_ctx_Is_g = (*env)->GetMethodID(env, clazz, "ctxIsg", "(JJ)I");
    if (jniMethod_ctx_Is_g == NULL) {
        LOGS("ERROR: Java method ctxIsg not found found !\n");
        return 1;
    }
    ctx->ctx_Is_g = &ctx_Is_g_jni;
    jniMethod_ctx_AsStruct = (*env)->GetMethodID(env, clazz, "ctxAsStruct", "(J)J");
    if (jniMethod_ctx_AsStruct == NULL) {
        LOGS("ERROR: Java method ctxAsStruct not found found !\n");
        return 1;
    }
    ctx->ctx_AsStruct = &ctx_AsStruct_jni;
    jniMethod_ctx_AsStructLegacy = (*env)->GetMethodID(env, clazz, "ctxAsStructLegacy", "(J)J");
    if (jniMethod_ctx_AsStructLegacy == NULL) {
        LOGS("ERROR: Java method ctxAsStructLegacy not found found !\n");
        return 1;
    }
    ctx->ctx_AsStructLegacy = &ctx_AsStructLegacy_jni;
    jniMethod_ctx_New = (*env)->GetMethodID(env, clazz, "ctxNew", "(JJ)J");
    if (jniMethod_ctx_New == NULL) {
        LOGS("ERROR: Java method ctxNew not found found !\n");
        return 1;
    }
    ctx->ctx_New = &ctx_New_jni;
    jniMethod_ctx_Repr = (*env)->GetMethodID(env, clazz, "ctxRepr", "(J)J");
    if (jniMethod_ctx_Repr == NULL) {
        LOGS("ERROR: Java method ctxRepr not found found !\n");
        return 1;
    }
    ctx->ctx_Repr = &ctx_Repr_jni;
    jniMethod_ctx_Str = (*env)->GetMethodID(env, clazz, "ctxStr", "(J)J");
    if (jniMethod_ctx_Str == NULL) {
        LOGS("ERROR: Java method ctxStr not found found !\n");
        return 1;
    }
    ctx->ctx_Str = &ctx_Str_jni;
    jniMethod_ctx_ASCII = (*env)->GetMethodID(env, clazz, "ctxASCII", "(J)J");
    if (jniMethod_ctx_ASCII == NULL) {
        LOGS("ERROR: Java method ctxASCII not found found !\n");
        return 1;
    }
    ctx->ctx_ASCII = &ctx_ASCII_jni;
    jniMethod_ctx_Bytes = (*env)->GetMethodID(env, clazz, "ctxBytes", "(J)J");
    if (jniMethod_ctx_Bytes == NULL) {
        LOGS("ERROR: Java method ctxBytes not found found !\n");
        return 1;
    }
    ctx->ctx_Bytes = &ctx_Bytes_jni;
    jniMethod_ctx_RichCompare = (*env)->GetMethodID(env, clazz, "ctxRichCompare", "(JJI)J");
    if (jniMethod_ctx_RichCompare == NULL) {
        LOGS("ERROR: Java method ctxRichCompare not found found !\n");
        return 1;
    }
    ctx->ctx_RichCompare = &ctx_RichCompare_jni;
    jniMethod_ctx_RichCompareBool = (*env)->GetMethodID(env, clazz, "ctxRichCompareBool", "(JJI)I");
    if (jniMethod_ctx_RichCompareBool == NULL) {
        LOGS("ERROR: Java method ctxRichCompareBool not found found !\n");
        return 1;
    }
    ctx->ctx_RichCompareBool = &ctx_RichCompareBool_jni;
    jniMethod_ctx_Hash = (*env)->GetMethodID(env, clazz, "ctxHash", "(J)J");
    if (jniMethod_ctx_Hash == NULL) {
        LOGS("ERROR: Java method ctxHash not found found !\n");
        return 1;
    }
    ctx->ctx_Hash = &ctx_Hash_jni;
    jniMethod_ctx_SeqIter_New = (*env)->GetMethodID(env, clazz, "ctxSeqIterNew", "(J)J");
    if (jniMethod_ctx_SeqIter_New == NULL) {
        LOGS("ERROR: Java method ctxSeqIterNew not found found !\n");
        return 1;
    }
    ctx->ctx_SeqIter_New = &ctx_SeqIter_New_jni;
    jniMethod_ctx_Bytes_Check = (*env)->GetMethodID(env, clazz, "ctxBytesCheck", "(J)I");
    if (jniMethod_ctx_Bytes_Check == NULL) {
        LOGS("ERROR: Java method ctxBytesCheck not found found !\n");
        return 1;
    }
    ctx->ctx_Bytes_Check = &ctx_Bytes_Check_jni;
    jniMethod_ctx_Bytes_Size = (*env)->GetMethodID(env, clazz, "ctxBytesSize", "(J)J");
    if (jniMethod_ctx_Bytes_Size == NULL) {
        LOGS("ERROR: Java method ctxBytesSize not found found !\n");
        return 1;
    }
    ctx->ctx_Bytes_Size = &ctx_Bytes_Size_jni;
    jniMethod_ctx_Bytes_GET_SIZE = (*env)->GetMethodID(env, clazz, "ctxBytesGETSIZE", "(J)J");
    if (jniMethod_ctx_Bytes_GET_SIZE == NULL) {
        LOGS("ERROR: Java method ctxBytesGETSIZE not found found !\n");
        return 1;
    }
    ctx->ctx_Bytes_GET_SIZE = &ctx_Bytes_GET_SIZE_jni;
    jniMethod_ctx_Bytes_AsString = (*env)->GetMethodID(env, clazz, "ctxBytesAsString", "(J)J");
    if (jniMethod_ctx_Bytes_AsString == NULL) {
        LOGS("ERROR: Java method ctxBytesAsString not found found !\n");
        return 1;
    }
    ctx->ctx_Bytes_AsString = &ctx_Bytes_AsString_jni;
    jniMethod_ctx_Bytes_AS_STRING = (*env)->GetMethodID(env, clazz, "ctxBytesASSTRING", "(J)J");
    if (jniMethod_ctx_Bytes_AS_STRING == NULL) {
        LOGS("ERROR: Java method ctxBytesASSTRING not found found !\n");
        return 1;
    }
    ctx->ctx_Bytes_AS_STRING = &ctx_Bytes_AS_STRING_jni;
    jniMethod_ctx_Bytes_FromString = (*env)->GetMethodID(env, clazz, "ctxBytesFromString", "(J)J");
    if (jniMethod_ctx_Bytes_FromString == NULL) {
        LOGS("ERROR: Java method ctxBytesFromString not found found !\n");
        return 1;
    }
    ctx->ctx_Bytes_FromString = &ctx_Bytes_FromString_jni;
    jniMethod_ctx_Bytes_FromStringAndSize = (*env)->GetMethodID(env, clazz, "ctxBytesFromStringAndSize", "(JJ)J");
    if (jniMethod_ctx_Bytes_FromStringAndSize == NULL) {
        LOGS("ERROR: Java method ctxBytesFromStringAndSize not found found !\n");
        return 1;
    }
    ctx->ctx_Bytes_FromStringAndSize = &ctx_Bytes_FromStringAndSize_jni;
    jniMethod_ctx_Unicode_FromString = (*env)->GetMethodID(env, clazz, "ctxUnicodeFromString", "(J)J");
    if (jniMethod_ctx_Unicode_FromString == NULL) {
        LOGS("ERROR: Java method ctxUnicodeFromString not found found !\n");
        return 1;
    }
    ctx->ctx_Unicode_FromString = &ctx_Unicode_FromString_jni;
    jniMethod_ctx_Unicode_Check = (*env)->GetMethodID(env, clazz, "ctxUnicodeCheck", "(J)I");
    if (jniMethod_ctx_Unicode_Check == NULL) {
        LOGS("ERROR: Java method ctxUnicodeCheck not found found !\n");
        return 1;
    }
    ctx->ctx_Unicode_Check = &ctx_Unicode_Check_jni;
    jniMethod_ctx_Unicode_AsASCIIString = (*env)->GetMethodID(env, clazz, "ctxUnicodeAsASCIIString", "(J)J");
    if (jniMethod_ctx_Unicode_AsASCIIString == NULL) {
        LOGS("ERROR: Java method ctxUnicodeAsASCIIString not found found !\n");
        return 1;
    }
    ctx->ctx_Unicode_AsASCIIString = &ctx_Unicode_AsASCIIString_jni;
    jniMethod_ctx_Unicode_AsLatin1String = (*env)->GetMethodID(env, clazz, "ctxUnicodeAsLatin1String", "(J)J");
    if (jniMethod_ctx_Unicode_AsLatin1String == NULL) {
        LOGS("ERROR: Java method ctxUnicodeAsLatin1String not found found !\n");
        return 1;
    }
    ctx->ctx_Unicode_AsLatin1String = &ctx_Unicode_AsLatin1String_jni;
    jniMethod_ctx_Unicode_AsUTF8String = (*env)->GetMethodID(env, clazz, "ctxUnicodeAsUTF8String", "(J)J");
    if (jniMethod_ctx_Unicode_AsUTF8String == NULL) {
        LOGS("ERROR: Java method ctxUnicodeAsUTF8String not found found !\n");
        return 1;
    }
    ctx->ctx_Unicode_AsUTF8String = &ctx_Unicode_AsUTF8String_jni;
    jniMethod_ctx_Unicode_AsUTF8AndSize = (*env)->GetMethodID(env, clazz, "ctxUnicodeAsUTF8AndSize", "(JJ)J");
    if (jniMethod_ctx_Unicode_AsUTF8AndSize == NULL) {
        LOGS("ERROR: Java method ctxUnicodeAsUTF8AndSize not found found !\n");
        return 1;
    }
    ctx->ctx_Unicode_AsUTF8AndSize = &ctx_Unicode_AsUTF8AndSize_jni;
    jniMethod_ctx_Unicode_FromWideChar = (*env)->GetMethodID(env, clazz, "ctxUnicodeFromWideChar", "(JJ)J");
    if (jniMethod_ctx_Unicode_FromWideChar == NULL) {
        LOGS("ERROR: Java method ctxUnicodeFromWideChar not found found !\n");
        return 1;
    }
    ctx->ctx_Unicode_FromWideChar = &ctx_Unicode_FromWideChar_jni;
    jniMethod_ctx_Unicode_DecodeFSDefault = (*env)->GetMethodID(env, clazz, "ctxUnicodeDecodeFSDefault", "(J)J");
    if (jniMethod_ctx_Unicode_DecodeFSDefault == NULL) {
        LOGS("ERROR: Java method ctxUnicodeDecodeFSDefault not found found !\n");
        return 1;
    }
    ctx->ctx_Unicode_DecodeFSDefault = &ctx_Unicode_DecodeFSDefault_jni;
    jniMethod_ctx_Unicode_DecodeFSDefaultAndSize = (*env)->GetMethodID(env, clazz, "ctxUnicodeDecodeFSDefaultAndSize", "(JJ)J");
    if (jniMethod_ctx_Unicode_DecodeFSDefaultAndSize == NULL) {
        LOGS("ERROR: Java method ctxUnicodeDecodeFSDefaultAndSize not found found !\n");
        return 1;
    }
    ctx->ctx_Unicode_DecodeFSDefaultAndSize = &ctx_Unicode_DecodeFSDefaultAndSize_jni;
    jniMethod_ctx_Unicode_EncodeFSDefault = (*env)->GetMethodID(env, clazz, "ctxUnicodeEncodeFSDefault", "(J)J");
    if (jniMethod_ctx_Unicode_EncodeFSDefault == NULL) {
        LOGS("ERROR: Java method ctxUnicodeEncodeFSDefault not found found !\n");
        return 1;
    }
    ctx->ctx_Unicode_EncodeFSDefault = &ctx_Unicode_EncodeFSDefault_jni;
    jniMethod_ctx_Unicode_ReadChar = (*env)->GetMethodID(env, clazz, "ctxUnicodeReadChar", "(JJ)J");
    if (jniMethod_ctx_Unicode_ReadChar == NULL) {
        LOGS("ERROR: Java method ctxUnicodeReadChar not found found !\n");
        return 1;
    }
    ctx->ctx_Unicode_ReadChar = &ctx_Unicode_ReadChar_jni;
    jniMethod_ctx_Unicode_DecodeASCII = (*env)->GetMethodID(env, clazz, "ctxUnicodeDecodeASCII", "(JJJ)J");
    if (jniMethod_ctx_Unicode_DecodeASCII == NULL) {
        LOGS("ERROR: Java method ctxUnicodeDecodeASCII not found found !\n");
        return 1;
    }
    ctx->ctx_Unicode_DecodeASCII = &ctx_Unicode_DecodeASCII_jni;
    jniMethod_ctx_Unicode_DecodeLatin1 = (*env)->GetMethodID(env, clazz, "ctxUnicodeDecodeLatin1", "(JJJ)J");
    if (jniMethod_ctx_Unicode_DecodeLatin1 == NULL) {
        LOGS("ERROR: Java method ctxUnicodeDecodeLatin1 not found found !\n");
        return 1;
    }
    ctx->ctx_Unicode_DecodeLatin1 = &ctx_Unicode_DecodeLatin1_jni;
    jniMethod_ctx_Unicode_FromEncodedObject = (*env)->GetMethodID(env, clazz, "ctxUnicodeFromEncodedObject", "(JJJ)J");
    if (jniMethod_ctx_Unicode_FromEncodedObject == NULL) {
        LOGS("ERROR: Java method ctxUnicodeFromEncodedObject not found found !\n");
        return 1;
    }
    ctx->ctx_Unicode_FromEncodedObject = &ctx_Unicode_FromEncodedObject_jni;
    jniMethod_ctx_Unicode_InternFromString = (*env)->GetMethodID(env, clazz, "ctxUnicodeInternFromString", "(J)J");
    if (jniMethod_ctx_Unicode_InternFromString == NULL) {
        LOGS("ERROR: Java method ctxUnicodeInternFromString not found found !\n");
        return 1;
    }
    ctx->ctx_Unicode_InternFromString = &ctx_Unicode_InternFromString_jni;
    jniMethod_ctx_Unicode_Substring = (*env)->GetMethodID(env, clazz, "ctxUnicodeSubstring", "(JJJ)J");
    if (jniMethod_ctx_Unicode_Substring == NULL) {
        LOGS("ERROR: Java method ctxUnicodeSubstring not found found !\n");
        return 1;
    }
    ctx->ctx_Unicode_Substring = &ctx_Unicode_Substring_jni;
    jniMethod_ctx_List_Check = (*env)->GetMethodID(env, clazz, "ctxListCheck", "(J)I");
    if (jniMethod_ctx_List_Check == NULL) {
        LOGS("ERROR: Java method ctxListCheck not found found !\n");
        return 1;
    }
    ctx->ctx_List_Check = &ctx_List_Check_jni;
    jniMethod_ctx_List_New = (*env)->GetMethodID(env, clazz, "ctxListNew", "(J)J");
    if (jniMethod_ctx_List_New == NULL) {
        LOGS("ERROR: Java method ctxListNew not found found !\n");
        return 1;
    }
    ctx->ctx_List_New = &ctx_List_New_jni;
    jniMethod_ctx_List_Append = (*env)->GetMethodID(env, clazz, "ctxListAppend", "(JJ)I");
    if (jniMethod_ctx_List_Append == NULL) {
        LOGS("ERROR: Java method ctxListAppend not found found !\n");
        return 1;
    }
    ctx->ctx_List_Append = &ctx_List_Append_jni;
    jniMethod_ctx_Dict_Check = (*env)->GetMethodID(env, clazz, "ctxDictCheck", "(J)I");
    if (jniMethod_ctx_Dict_Check == NULL) {
        LOGS("ERROR: Java method ctxDictCheck not found found !\n");
        return 1;
    }
    ctx->ctx_Dict_Check = &ctx_Dict_Check_jni;
    jniMethod_ctx_Dict_New = (*env)->GetMethodID(env, clazz, "ctxDictNew", "()J");
    if (jniMethod_ctx_Dict_New == NULL) {
        LOGS("ERROR: Java method ctxDictNew not found found !\n");
        return 1;
    }
    ctx->ctx_Dict_New = &ctx_Dict_New_jni;
    jniMethod_ctx_Dict_Keys = (*env)->GetMethodID(env, clazz, "ctxDictKeys", "(J)J");
    if (jniMethod_ctx_Dict_Keys == NULL) {
        LOGS("ERROR: Java method ctxDictKeys not found found !\n");
        return 1;
    }
    ctx->ctx_Dict_Keys = &ctx_Dict_Keys_jni;
    jniMethod_ctx_Dict_GetItem = (*env)->GetMethodID(env, clazz, "ctxDictGetItem", "(JJ)J");
    if (jniMethod_ctx_Dict_GetItem == NULL) {
        LOGS("ERROR: Java method ctxDictGetItem not found found !\n");
        return 1;
    }
    ctx->ctx_Dict_GetItem = &ctx_Dict_GetItem_jni;
    jniMethod_ctx_Tuple_Check = (*env)->GetMethodID(env, clazz, "ctxTupleCheck", "(J)I");
    if (jniMethod_ctx_Tuple_Check == NULL) {
        LOGS("ERROR: Java method ctxTupleCheck not found found !\n");
        return 1;
    }
    ctx->ctx_Tuple_Check = &ctx_Tuple_Check_jni;
    jniMethod_ctx_Tuple_FromArray = (*env)->GetMethodID(env, clazz, "ctxTupleFromArray", "(JJ)J");
    if (jniMethod_ctx_Tuple_FromArray == NULL) {
        LOGS("ERROR: Java method ctxTupleFromArray not found found !\n");
        return 1;
    }
    ctx->ctx_Tuple_FromArray = &ctx_Tuple_FromArray_jni;
    jniMethod_ctx_Slice_Unpack = (*env)->GetMethodID(env, clazz, "ctxSliceUnpack", "(JJJJ)I");
    if (jniMethod_ctx_Slice_Unpack == NULL) {
        LOGS("ERROR: Java method ctxSliceUnpack not found found !\n");
        return 1;
    }
    ctx->ctx_Slice_Unpack = &ctx_Slice_Unpack_jni;
    jniMethod_ctx_ContextVar_New = (*env)->GetMethodID(env, clazz, "ctxContextVarNew", "(JJ)J");
    if (jniMethod_ctx_ContextVar_New == NULL) {
        LOGS("ERROR: Java method ctxContextVarNew not found found !\n");
        return 1;
    }
    ctx->ctx_ContextVar_New = &ctx_ContextVar_New_jni;
    jniMethod_ctx_ContextVar_Get = (*env)->GetMethodID(env, clazz, "ctxContextVarGet", "(JJJ)I");
    if (jniMethod_ctx_ContextVar_Get == NULL) {
        LOGS("ERROR: Java method ctxContextVarGet not found found !\n");
        return 1;
    }
    ctx->ctx_ContextVar_Get = &ctx_ContextVar_Get_jni;
    jniMethod_ctx_ContextVar_Set = (*env)->GetMethodID(env, clazz, "ctxContextVarSet", "(JJ)J");
    if (jniMethod_ctx_ContextVar_Set == NULL) {
        LOGS("ERROR: Java method ctxContextVarSet not found found !\n");
        return 1;
    }
    ctx->ctx_ContextVar_Set = &ctx_ContextVar_Set_jni;
    jniMethod_ctx_Import_ImportModule = (*env)->GetMethodID(env, clazz, "ctxImportImportModule", "(J)J");
    if (jniMethod_ctx_Import_ImportModule == NULL) {
        LOGS("ERROR: Java method ctxImportImportModule not found found !\n");
        return 1;
    }
    ctx->ctx_Import_ImportModule = &ctx_Import_ImportModule_jni;
    jniMethod_ctx_Capsule_New = (*env)->GetMethodID(env, clazz, "ctxCapsuleNew", "(JJJ)J");
    if (jniMethod_ctx_Capsule_New == NULL) {
        LOGS("ERROR: Java method ctxCapsuleNew not found found !\n");
        return 1;
    }
    ctx->ctx_Capsule_New = &ctx_Capsule_New_jni;
    jniMethod_ctx_Capsule_Get = (*env)->GetMethodID(env, clazz, "ctxCapsuleGet", "(JIJ)J");
    if (jniMethod_ctx_Capsule_Get == NULL) {
        LOGS("ERROR: Java method ctxCapsuleGet not found found !\n");
        return 1;
    }
    ctx->ctx_Capsule_Get = &ctx_Capsule_Get_jni;
    jniMethod_ctx_Capsule_IsValid = (*env)->GetMethodID(env, clazz, "ctxCapsuleIsValid", "(JJ)I");
    if (jniMethod_ctx_Capsule_IsValid == NULL) {
        LOGS("ERROR: Java method ctxCapsuleIsValid not found found !\n");
        return 1;
    }
    ctx->ctx_Capsule_IsValid = &ctx_Capsule_IsValid_jni;
    jniMethod_ctx_Capsule_Set = (*env)->GetMethodID(env, clazz, "ctxCapsuleSet", "(JIJ)I");
    if (jniMethod_ctx_Capsule_Set == NULL) {
        LOGS("ERROR: Java method ctxCapsuleSet not found found !\n");
        return 1;
    }
    ctx->ctx_Capsule_Set = &ctx_Capsule_Set_jni;
    jniMethod_ctx_FromPyObject = (*env)->GetMethodID(env, clazz, "ctxFromPyObject", "(J)J");
    if (jniMethod_ctx_FromPyObject == NULL) {
        LOGS("ERROR: Java method ctxFromPyObject not found found !\n");
        return 1;
    }
    ctx->ctx_FromPyObject = &ctx_FromPyObject_jni;
    jniMethod_ctx_AsPyObject = (*env)->GetMethodID(env, clazz, "ctxAsPyObject", "(J)J");
    if (jniMethod_ctx_AsPyObject == NULL) {
        LOGS("ERROR: Java method ctxAsPyObject not found found !\n");
        return 1;
    }
    ctx->ctx_AsPyObject = &ctx_AsPyObject_jni;
    jniMethod_ctx_ListBuilder_New = (*env)->GetMethodID(env, clazz, "ctxListBuilderNew", "(J)J");
    if (jniMethod_ctx_ListBuilder_New == NULL) {
        LOGS("ERROR: Java method ctxListBuilderNew not found found !\n");
        return 1;
    }
    ctx->ctx_ListBuilder_New = &ctx_ListBuilder_New_jni;
    jniMethod_ctx_ListBuilder_Set = (*env)->GetMethodID(env, clazz, "ctxListBuilderSet", "(JJJ)V");
    if (jniMethod_ctx_ListBuilder_Set == NULL) {
        LOGS("ERROR: Java method ctxListBuilderSet not found found !\n");
        return 1;
    }
    ctx->ctx_ListBuilder_Set = &ctx_ListBuilder_Set_jni;
    jniMethod_ctx_ListBuilder_Build = (*env)->GetMethodID(env, clazz, "ctxListBuilderBuild", "(J)J");
    if (jniMethod_ctx_ListBuilder_Build == NULL) {
        LOGS("ERROR: Java method ctxListBuilderBuild not found found !\n");
        return 1;
    }
    ctx->ctx_ListBuilder_Build = &ctx_ListBuilder_Build_jni;
    jniMethod_ctx_ListBuilder_Cancel = (*env)->GetMethodID(env, clazz, "ctxListBuilderCancel", "(J)V");
    if (jniMethod_ctx_ListBuilder_Cancel == NULL) {
        LOGS("ERROR: Java method ctxListBuilderCancel not found found !\n");
        return 1;
    }
    ctx->ctx_ListBuilder_Cancel = &ctx_ListBuilder_Cancel_jni;
    jniMethod_ctx_TupleBuilder_New = (*env)->GetMethodID(env, clazz, "ctxTupleBuilderNew", "(J)J");
    if (jniMethod_ctx_TupleBuilder_New == NULL) {
        LOGS("ERROR: Java method ctxTupleBuilderNew not found found !\n");
        return 1;
    }
    ctx->ctx_TupleBuilder_New = &ctx_TupleBuilder_New_jni;
    jniMethod_ctx_TupleBuilder_Set = (*env)->GetMethodID(env, clazz, "ctxTupleBuilderSet", "(JJJ)V");
    if (jniMethod_ctx_TupleBuilder_Set == NULL) {
        LOGS("ERROR: Java method ctxTupleBuilderSet not found found !\n");
        return 1;
    }
    ctx->ctx_TupleBuilder_Set = &ctx_TupleBuilder_Set_jni;
    jniMethod_ctx_TupleBuilder_Build = (*env)->GetMethodID(env, clazz, "ctxTupleBuilderBuild", "(J)J");
    if (jniMethod_ctx_TupleBuilder_Build == NULL) {
        LOGS("ERROR: Java method ctxTupleBuilderBuild not found found !\n");
        return 1;
    }
    ctx->ctx_TupleBuilder_Build = &ctx_TupleBuilder_Build_jni;
    jniMethod_ctx_TupleBuilder_Cancel = (*env)->GetMethodID(env, clazz, "ctxTupleBuilderCancel", "(J)V");
    if (jniMethod_ctx_TupleBuilder_Cancel == NULL) {
        LOGS("ERROR: Java method ctxTupleBuilderCancel not found found !\n");
        return 1;
    }
    ctx->ctx_TupleBuilder_Cancel = &ctx_TupleBuilder_Cancel_jni;
    jniMethod_ctx_Tracker_New = (*env)->GetMethodID(env, clazz, "ctxTrackerNew", "(J)J");
    if (jniMethod_ctx_Tracker_New == NULL) {
        LOGS("ERROR: Java method ctxTrackerNew not found found !\n");
        return 1;
    }
    ctx->ctx_Tracker_New = &ctx_Tracker_New_jni;
    jniMethod_ctx_Tracker_Add = (*env)->GetMethodID(env, clazz, "ctxTrackerAdd", "(JJ)I");
    if (jniMethod_ctx_Tracker_Add == NULL) {
        LOGS("ERROR: Java method ctxTrackerAdd not found found !\n");
        return 1;
    }
    ctx->ctx_Tracker_Add = &ctx_Tracker_Add_jni;
    jniMethod_ctx_Tracker_ForgetAll = (*env)->GetMethodID(env, clazz, "ctxTrackerForgetAll", "(J)V");
    if (jniMethod_ctx_Tracker_ForgetAll == NULL) {
        LOGS("ERROR: Java method ctxTrackerForgetAll not found found !\n");
        return 1;
    }
    ctx->ctx_Tracker_ForgetAll = &ctx_Tracker_ForgetAll_jni;
    jniMethod_ctx_Tracker_Close = (*env)->GetMethodID(env, clazz, "ctxTrackerClose", "(J)V");
    if (jniMethod_ctx_Tracker_Close == NULL) {
        LOGS("ERROR: Java method ctxTrackerClose not found found !\n");
        return 1;
    }
    ctx->ctx_Tracker_Close = &ctx_Tracker_Close_jni;
    jniMethod_ctx_Field_Store = (*env)->GetMethodID(env, clazz, "ctxFieldStore", "(JJJ)V");
    if (jniMethod_ctx_Field_Store == NULL) {
        LOGS("ERROR: Java method ctxFieldStore not found found !\n");
        return 1;
    }
    ctx->ctx_Field_Store = &ctx_Field_Store_jni;
    jniMethod_ctx_Field_Load = (*env)->GetMethodID(env, clazz, "ctxFieldLoad", "(JJ)J");
    if (jniMethod_ctx_Field_Load == NULL) {
        LOGS("ERROR: Java method ctxFieldLoad not found found !\n");
        return 1;
    }
    ctx->ctx_Field_Load = &ctx_Field_Load_jni;
    jniMethod_ctx_ReenterPythonExecution = (*env)->GetMethodID(env, clazz, "ctxReenterPythonExecution", "(J)V");
    if (jniMethod_ctx_ReenterPythonExecution == NULL) {
        LOGS("ERROR: Java method ctxReenterPythonExecution not found found !\n");
        return 1;
    }
    ctx->ctx_ReenterPythonExecution = &ctx_ReenterPythonExecution_jni;
    jniMethod_ctx_LeavePythonExecution = (*env)->GetMethodID(env, clazz, "ctxLeavePythonExecution", "()J");
    if (jniMethod_ctx_LeavePythonExecution == NULL) {
        LOGS("ERROR: Java method ctxLeavePythonExecution not found found !\n");
        return 1;
    }
    ctx->ctx_LeavePythonExecution = &ctx_LeavePythonExecution_jni;
    jniMethod_ctx_Global_Store = (*env)->GetMethodID(env, clazz, "ctxGlobalStore", "(JJ)V");
    if (jniMethod_ctx_Global_Store == NULL) {
        LOGS("ERROR: Java method ctxGlobalStore not found found !\n");
        return 1;
    }
    ctx->ctx_Global_Store = &ctx_Global_Store_jni;
    jniMethod_ctx_Global_Load = (*env)->GetMethodID(env, clazz, "ctxGlobalLoad", "(J)J");
    if (jniMethod_ctx_Global_Load == NULL) {
        LOGS("ERROR: Java method ctxGlobalLoad not found found !\n");
        return 1;
    }
    ctx->ctx_Global_Load = &ctx_Global_Load_jni;
    jniMethod_ctx_Dump = (*env)->GetMethodID(env, clazz, "ctxDump", "(J)V");
    if (jniMethod_ctx_Dump == NULL) {
        LOGS("ERROR: Java method ctxDump not found found !\n");
        return 1;
    }
    ctx->ctx_Dump = &ctx_Dump_jni;
    jniMethod_ctx_Type_CheckSlot = (*env)->GetMethodID(env, clazz, "ctxTypeCheckSlot", "(JJ)I");
    if (jniMethod_ctx_Type_CheckSlot == NULL) {
        LOGS("ERROR: Java method ctxTypeCheckSlot not found found !\n");
        return 1;
    }
    ctx->ctx_Type_CheckSlot = &ctx_Type_CheckSlot_jni;
    return 0;
}

HPy ctx_Module_Create_jni(HPyContext *ctx, HPyModuleDef *def)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Module_Create, PTR_UP(def));
}

HPy ctx_Dup_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Dup, HPY_UP(h));
}

void ctx_Close_jni(HPyContext *ctx, HPy h)
{
    DO_UPCALL_VOID(CONTEXT_INSTANCE(ctx), ctx_Close, HPY_UP(h));
}

HPy ctx_Long_FromLong_jni(HPyContext *ctx, long value)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Long_FromLong, LONG_UP(value));
}

HPy ctx_Long_FromUnsignedLong_jni(HPyContext *ctx, unsigned long value)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Long_FromUnsignedLong, LONG_UP(value));
}

HPy ctx_Long_FromLongLong_jni(HPyContext *ctx, long long v)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Long_FromLongLong, LONG_UP(v));
}

HPy ctx_Long_FromUnsignedLongLong_jni(HPyContext *ctx, unsigned long long v)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Long_FromUnsignedLongLong, LONG_UP(v));
}

HPy ctx_Long_FromSize_t_jni(HPyContext *ctx, size_t value)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Long_FromSize_t, LONG_UP(value));
}

HPy ctx_Long_FromSsize_t_jni(HPyContext *ctx, HPy_ssize_t value)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Long_FromSsize_t, SIZE_T_UP(value));
}

long ctx_Long_AsLong_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_LONG(CONTEXT_INSTANCE(ctx), ctx_Long_AsLong, HPY_UP(h));
}

unsigned long ctx_Long_AsUnsignedLong_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_UNSIGNED_LONG(CONTEXT_INSTANCE(ctx), ctx_Long_AsUnsignedLong, HPY_UP(h));
}

unsigned long ctx_Long_AsUnsignedLongMask_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_UNSIGNED_LONG(CONTEXT_INSTANCE(ctx), ctx_Long_AsUnsignedLongMask, HPY_UP(h));
}

long long ctx_Long_AsLongLong_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_LONG_LONG(CONTEXT_INSTANCE(ctx), ctx_Long_AsLongLong, HPY_UP(h));
}

unsigned long long ctx_Long_AsUnsignedLongLong_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_UNSIGNED_LONG_LONG(CONTEXT_INSTANCE(ctx), ctx_Long_AsUnsignedLongLong, HPY_UP(h));
}

unsigned long long ctx_Long_AsUnsignedLongLongMask_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_UNSIGNED_LONG_LONG(CONTEXT_INSTANCE(ctx), ctx_Long_AsUnsignedLongLongMask, HPY_UP(h));
}

size_t ctx_Long_AsSize_t_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_SIZE_T(CONTEXT_INSTANCE(ctx), ctx_Long_AsSize_t, HPY_UP(h));
}

HPy_ssize_t ctx_Long_AsSsize_t_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_HPY_SSIZE_T(CONTEXT_INSTANCE(ctx), ctx_Long_AsSsize_t, HPY_UP(h));
}

void *ctx_Long_AsVoidPtr_jni(HPyContext *ctx, HPy h)
{
    return (void *)DO_UPCALL_PTR(CONTEXT_INSTANCE(ctx), ctx_Long_AsVoidPtr, HPY_UP(h));
}

double ctx_Long_AsDouble_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_DOUBLE(CONTEXT_INSTANCE(ctx), ctx_Long_AsDouble, HPY_UP(h));
}

HPy ctx_Float_FromDouble_jni(HPyContext *ctx, double v)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Float_FromDouble, DOUBLE_UP(v));
}

double ctx_Float_AsDouble_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_DOUBLE(CONTEXT_INSTANCE(ctx), ctx_Float_AsDouble, HPY_UP(h));
}

HPy ctx_Bool_FromLong_jni(HPyContext *ctx, long v)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Bool_FromLong, LONG_UP(v));
}

HPy_ssize_t ctx_Length_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_HPY_SSIZE_T(CONTEXT_INSTANCE(ctx), ctx_Length, HPY_UP(h));
}

int ctx_Sequence_Check_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_Sequence_Check, HPY_UP(h));
}

int ctx_Number_Check_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_Number_Check, HPY_UP(h));
}

HPy ctx_Add_jni(HPyContext *ctx, HPy h1, HPy h2)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Add, HPY_UP(h1), HPY_UP(h2));
}

HPy ctx_Subtract_jni(HPyContext *ctx, HPy h1, HPy h2)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Subtract, HPY_UP(h1), HPY_UP(h2));
}

HPy ctx_Multiply_jni(HPyContext *ctx, HPy h1, HPy h2)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Multiply, HPY_UP(h1), HPY_UP(h2));
}

HPy ctx_MatrixMultiply_jni(HPyContext *ctx, HPy h1, HPy h2)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_MatrixMultiply, HPY_UP(h1), HPY_UP(h2));
}

HPy ctx_FloorDivide_jni(HPyContext *ctx, HPy h1, HPy h2)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_FloorDivide, HPY_UP(h1), HPY_UP(h2));
}

HPy ctx_TrueDivide_jni(HPyContext *ctx, HPy h1, HPy h2)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_TrueDivide, HPY_UP(h1), HPY_UP(h2));
}

HPy ctx_Remainder_jni(HPyContext *ctx, HPy h1, HPy h2)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Remainder, HPY_UP(h1), HPY_UP(h2));
}

HPy ctx_Divmod_jni(HPyContext *ctx, HPy h1, HPy h2)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Divmod, HPY_UP(h1), HPY_UP(h2));
}

HPy ctx_Power_jni(HPyContext *ctx, HPy h1, HPy h2, HPy h3)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Power, HPY_UP(h1), HPY_UP(h2), HPY_UP(h3));
}

HPy ctx_Negative_jni(HPyContext *ctx, HPy h1)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Negative, HPY_UP(h1));
}

HPy ctx_Positive_jni(HPyContext *ctx, HPy h1)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Positive, HPY_UP(h1));
}

HPy ctx_Absolute_jni(HPyContext *ctx, HPy h1)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Absolute, HPY_UP(h1));
}

HPy ctx_Invert_jni(HPyContext *ctx, HPy h1)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Invert, HPY_UP(h1));
}

HPy ctx_Lshift_jni(HPyContext *ctx, HPy h1, HPy h2)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Lshift, HPY_UP(h1), HPY_UP(h2));
}

HPy ctx_Rshift_jni(HPyContext *ctx, HPy h1, HPy h2)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Rshift, HPY_UP(h1), HPY_UP(h2));
}

HPy ctx_And_jni(HPyContext *ctx, HPy h1, HPy h2)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_And, HPY_UP(h1), HPY_UP(h2));
}

HPy ctx_Xor_jni(HPyContext *ctx, HPy h1, HPy h2)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Xor, HPY_UP(h1), HPY_UP(h2));
}

HPy ctx_Or_jni(HPyContext *ctx, HPy h1, HPy h2)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Or, HPY_UP(h1), HPY_UP(h2));
}

HPy ctx_Index_jni(HPyContext *ctx, HPy h1)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Index, HPY_UP(h1));
}

HPy ctx_Long_jni(HPyContext *ctx, HPy h1)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Long, HPY_UP(h1));
}

HPy ctx_Float_jni(HPyContext *ctx, HPy h1)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Float, HPY_UP(h1));
}

HPy ctx_InPlaceAdd_jni(HPyContext *ctx, HPy h1, HPy h2)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_InPlaceAdd, HPY_UP(h1), HPY_UP(h2));
}

HPy ctx_InPlaceSubtract_jni(HPyContext *ctx, HPy h1, HPy h2)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_InPlaceSubtract, HPY_UP(h1), HPY_UP(h2));
}

HPy ctx_InPlaceMultiply_jni(HPyContext *ctx, HPy h1, HPy h2)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_InPlaceMultiply, HPY_UP(h1), HPY_UP(h2));
}

HPy ctx_InPlaceMatrixMultiply_jni(HPyContext *ctx, HPy h1, HPy h2)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_InPlaceMatrixMultiply, HPY_UP(h1), HPY_UP(h2));
}

HPy ctx_InPlaceFloorDivide_jni(HPyContext *ctx, HPy h1, HPy h2)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_InPlaceFloorDivide, HPY_UP(h1), HPY_UP(h2));
}

HPy ctx_InPlaceTrueDivide_jni(HPyContext *ctx, HPy h1, HPy h2)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_InPlaceTrueDivide, HPY_UP(h1), HPY_UP(h2));
}

HPy ctx_InPlaceRemainder_jni(HPyContext *ctx, HPy h1, HPy h2)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_InPlaceRemainder, HPY_UP(h1), HPY_UP(h2));
}

HPy ctx_InPlacePower_jni(HPyContext *ctx, HPy h1, HPy h2, HPy h3)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_InPlacePower, HPY_UP(h1), HPY_UP(h2), HPY_UP(h3));
}

HPy ctx_InPlaceLshift_jni(HPyContext *ctx, HPy h1, HPy h2)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_InPlaceLshift, HPY_UP(h1), HPY_UP(h2));
}

HPy ctx_InPlaceRshift_jni(HPyContext *ctx, HPy h1, HPy h2)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_InPlaceRshift, HPY_UP(h1), HPY_UP(h2));
}

HPy ctx_InPlaceAnd_jni(HPyContext *ctx, HPy h1, HPy h2)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_InPlaceAnd, HPY_UP(h1), HPY_UP(h2));
}

HPy ctx_InPlaceXor_jni(HPyContext *ctx, HPy h1, HPy h2)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_InPlaceXor, HPY_UP(h1), HPY_UP(h2));
}

HPy ctx_InPlaceOr_jni(HPyContext *ctx, HPy h1, HPy h2)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_InPlaceOr, HPY_UP(h1), HPY_UP(h2));
}

int ctx_Callable_Check_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_Callable_Check, HPY_UP(h));
}

HPy ctx_CallTupleDict_jni(HPyContext *ctx, HPy callable, HPy args, HPy kw)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_CallTupleDict, HPY_UP(callable), HPY_UP(args), HPY_UP(kw));
}

void ctx_FatalError_jni(HPyContext *ctx, const char *message)
{
    DO_UPCALL_VOID(CONTEXT_INSTANCE(ctx), ctx_FatalError, PTR_UP(message));
}

void ctx_Err_SetString_jni(HPyContext *ctx, HPy h_type, const char *message)
{
    DO_UPCALL_VOID(CONTEXT_INSTANCE(ctx), ctx_Err_SetString, HPY_UP(h_type), PTR_UP(message));
}

void ctx_Err_SetObject_jni(HPyContext *ctx, HPy h_type, HPy h_value)
{
    DO_UPCALL_VOID(CONTEXT_INSTANCE(ctx), ctx_Err_SetObject, HPY_UP(h_type), HPY_UP(h_value));
}

HPy ctx_Err_SetFromErrnoWithFilename_jni(HPyContext *ctx, HPy h_type, const char *filename_fsencoded)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Err_SetFromErrnoWithFilename, HPY_UP(h_type), PTR_UP(filename_fsencoded));
}

void ctx_Err_SetFromErrnoWithFilenameObjects_jni(HPyContext *ctx, HPy h_type, HPy filename1, HPy filename2)
{
    DO_UPCALL_VOID(CONTEXT_INSTANCE(ctx), ctx_Err_SetFromErrnoWithFilenameObjects, HPY_UP(h_type), HPY_UP(filename1), HPY_UP(filename2));
}

int ctx_Err_Occurred_jni(HPyContext *ctx)
{
    return DO_UPCALL_INT0(CONTEXT_INSTANCE(ctx), ctx_Err_Occurred);
}

int ctx_Err_ExceptionMatches_jni(HPyContext *ctx, HPy exc)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_Err_ExceptionMatches, HPY_UP(exc));
}

void ctx_Err_NoMemory_jni(HPyContext *ctx)
{
    DO_UPCALL_VOID0(CONTEXT_INSTANCE(ctx), ctx_Err_NoMemory);
}

void ctx_Err_Clear_jni(HPyContext *ctx)
{
    DO_UPCALL_VOID0(CONTEXT_INSTANCE(ctx), ctx_Err_Clear);
}

HPy ctx_Err_NewException_jni(HPyContext *ctx, const char *name, HPy base, HPy dict)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Err_NewException, PTR_UP(name), HPY_UP(base), HPY_UP(dict));
}

HPy ctx_Err_NewExceptionWithDoc_jni(HPyContext *ctx, const char *name, const char *doc, HPy base, HPy dict)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Err_NewExceptionWithDoc, PTR_UP(name), PTR_UP(doc), HPY_UP(base), HPY_UP(dict));
}

int ctx_Err_WarnEx_jni(HPyContext *ctx, HPy category, const char *message, HPy_ssize_t stack_level)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_Err_WarnEx, HPY_UP(category), PTR_UP(message), SIZE_T_UP(stack_level));
}

void ctx_Err_WriteUnraisable_jni(HPyContext *ctx, HPy obj)
{
    DO_UPCALL_VOID(CONTEXT_INSTANCE(ctx), ctx_Err_WriteUnraisable, HPY_UP(obj));
}

int ctx_IsTrue_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_IsTrue, HPY_UP(h));
}

HPy ctx_Type_FromSpec_jni(HPyContext *ctx, HPyType_Spec *spec, HPyType_SpecParam *params)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Type_FromSpec, PTR_UP(spec), PTR_UP(params));
}

HPy ctx_Type_GenericNew_jni(HPyContext *ctx, HPy type, HPy *args, HPy_ssize_t nargs, HPy kw)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Type_GenericNew, HPY_UP(type), PTR_UP(args), SIZE_T_UP(nargs), HPY_UP(kw));
}

HPy ctx_GetAttr_jni(HPyContext *ctx, HPy obj, HPy name)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_GetAttr, HPY_UP(obj), HPY_UP(name));
}

HPy ctx_GetAttr_s_jni(HPyContext *ctx, HPy obj, const char *name)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_GetAttr_s, HPY_UP(obj), PTR_UP(name));
}

HPy ctx_MaybeGetAttr_s_jni(HPyContext *ctx, HPy obj, const char *name)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_MaybeGetAttr_s, HPY_UP(obj), PTR_UP(name));
}

int ctx_HasAttr_jni(HPyContext *ctx, HPy obj, HPy name)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_HasAttr, HPY_UP(obj), HPY_UP(name));
}

int ctx_HasAttr_s_jni(HPyContext *ctx, HPy obj, const char *name)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_HasAttr_s, HPY_UP(obj), PTR_UP(name));
}

int ctx_SetAttr_jni(HPyContext *ctx, HPy obj, HPy name, HPy value)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_SetAttr, HPY_UP(obj), HPY_UP(name), HPY_UP(value));
}

int ctx_SetAttr_s_jni(HPyContext *ctx, HPy obj, const char *name, HPy value)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_SetAttr_s, HPY_UP(obj), PTR_UP(name), HPY_UP(value));
}

HPy ctx_GetItem_jni(HPyContext *ctx, HPy obj, HPy key)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_GetItem, HPY_UP(obj), HPY_UP(key));
}

HPy ctx_GetItem_i_jni(HPyContext *ctx, HPy obj, HPy_ssize_t idx)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_GetItem_i, HPY_UP(obj), SIZE_T_UP(idx));
}

HPy ctx_GetItem_s_jni(HPyContext *ctx, HPy obj, const char *key)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_GetItem_s, HPY_UP(obj), PTR_UP(key));
}

int ctx_Contains_jni(HPyContext *ctx, HPy container, HPy key)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_Contains, HPY_UP(container), HPY_UP(key));
}

int ctx_SetItem_jni(HPyContext *ctx, HPy obj, HPy key, HPy value)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_SetItem, HPY_UP(obj), HPY_UP(key), HPY_UP(value));
}

int ctx_SetItem_i_jni(HPyContext *ctx, HPy obj, HPy_ssize_t idx, HPy value)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_SetItem_i, HPY_UP(obj), SIZE_T_UP(idx), HPY_UP(value));
}

int ctx_SetItem_s_jni(HPyContext *ctx, HPy obj, const char *key, HPy value)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_SetItem_s, HPY_UP(obj), PTR_UP(key), HPY_UP(value));
}

HPy ctx_Type_jni(HPyContext *ctx, HPy obj)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Type, HPY_UP(obj));
}

int ctx_TypeCheck_jni(HPyContext *ctx, HPy obj, HPy type)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_TypeCheck, HPY_UP(obj), HPY_UP(type));
}

int ctx_TypeCheck_g_jni(HPyContext *ctx, HPy obj, HPyGlobal type)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_TypeCheck_g, HPY_UP(obj), HPY_GLOBAL_UP(type));
}

int ctx_SetType_jni(HPyContext *ctx, HPy obj, HPy type)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_SetType, HPY_UP(obj), HPY_UP(type));
}

int ctx_Type_IsSubtype_jni(HPyContext *ctx, HPy sub, HPy type)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_Type_IsSubtype, HPY_UP(sub), HPY_UP(type));
}

const char *ctx_Type_GetName_jni(HPyContext *ctx, HPy type)
{
    return (const char *)DO_UPCALL_PTR(CONTEXT_INSTANCE(ctx), ctx_Type_GetName, HPY_UP(type));
}

int ctx_Is_jni(HPyContext *ctx, HPy obj, HPy other)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_Is, HPY_UP(obj), HPY_UP(other));
}

int ctx_Is_g_jni(HPyContext *ctx, HPy obj, HPyGlobal other)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_Is_g, HPY_UP(obj), HPY_GLOBAL_UP(other));
}

void *ctx_AsStruct_jni(HPyContext *ctx, HPy h)
{
    return (void *)DO_UPCALL_PTR(CONTEXT_INSTANCE(ctx), ctx_AsStruct, HPY_UP(h));
}

void *ctx_AsStructLegacy_jni(HPyContext *ctx, HPy h)
{
    return (void *)DO_UPCALL_PTR(CONTEXT_INSTANCE(ctx), ctx_AsStructLegacy, HPY_UP(h));
}

HPy ctx_New_jni(HPyContext *ctx, HPy h_type, void **data)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_New, HPY_UP(h_type), PTR_UP(data));
}

HPy ctx_Repr_jni(HPyContext *ctx, HPy obj)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Repr, HPY_UP(obj));
}

HPy ctx_Str_jni(HPyContext *ctx, HPy obj)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Str, HPY_UP(obj));
}

HPy ctx_ASCII_jni(HPyContext *ctx, HPy obj)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_ASCII, HPY_UP(obj));
}

HPy ctx_Bytes_jni(HPyContext *ctx, HPy obj)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Bytes, HPY_UP(obj));
}

HPy ctx_RichCompare_jni(HPyContext *ctx, HPy v, HPy w, int op)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_RichCompare, HPY_UP(v), HPY_UP(w), INT_UP(op));
}

int ctx_RichCompareBool_jni(HPyContext *ctx, HPy v, HPy w, int op)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_RichCompareBool, HPY_UP(v), HPY_UP(w), INT_UP(op));
}

HPy_hash_t ctx_Hash_jni(HPyContext *ctx, HPy obj)
{
    return DO_UPCALL_HPY_HASH_T(CONTEXT_INSTANCE(ctx), ctx_Hash, HPY_UP(obj));
}

HPy ctx_SeqIter_New_jni(HPyContext *ctx, HPy seq)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_SeqIter_New, HPY_UP(seq));
}

int ctx_Bytes_Check_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_Bytes_Check, HPY_UP(h));
}

HPy_ssize_t ctx_Bytes_Size_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_HPY_SSIZE_T(CONTEXT_INSTANCE(ctx), ctx_Bytes_Size, HPY_UP(h));
}

HPy_ssize_t ctx_Bytes_GET_SIZE_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_HPY_SSIZE_T(CONTEXT_INSTANCE(ctx), ctx_Bytes_GET_SIZE, HPY_UP(h));
}

char *ctx_Bytes_AsString_jni(HPyContext *ctx, HPy h)
{
    return (char *)DO_UPCALL_PTR(CONTEXT_INSTANCE(ctx), ctx_Bytes_AsString, HPY_UP(h));
}

char *ctx_Bytes_AS_STRING_jni(HPyContext *ctx, HPy h)
{
    return (char *)DO_UPCALL_PTR(CONTEXT_INSTANCE(ctx), ctx_Bytes_AS_STRING, HPY_UP(h));
}

HPy ctx_Bytes_FromString_jni(HPyContext *ctx, const char *v)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Bytes_FromString, PTR_UP(v));
}

HPy ctx_Bytes_FromStringAndSize_jni(HPyContext *ctx, const char *v, HPy_ssize_t len)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Bytes_FromStringAndSize, PTR_UP(v), SIZE_T_UP(len));
}

HPy ctx_Unicode_FromString_jni(HPyContext *ctx, const char *utf8)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Unicode_FromString, PTR_UP(utf8));
}

int ctx_Unicode_Check_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_Unicode_Check, HPY_UP(h));
}

HPy ctx_Unicode_AsASCIIString_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Unicode_AsASCIIString, HPY_UP(h));
}

HPy ctx_Unicode_AsLatin1String_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Unicode_AsLatin1String, HPY_UP(h));
}

HPy ctx_Unicode_AsUTF8String_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Unicode_AsUTF8String, HPY_UP(h));
}

const char *ctx_Unicode_AsUTF8AndSize_jni(HPyContext *ctx, HPy h, HPy_ssize_t *size)
{
    return (const char *)DO_UPCALL_PTR(CONTEXT_INSTANCE(ctx), ctx_Unicode_AsUTF8AndSize, HPY_UP(h), PTR_UP(size));
}

HPy ctx_Unicode_FromWideChar_jni(HPyContext *ctx, const wchar_t *w, HPy_ssize_t size)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Unicode_FromWideChar, PTR_UP(w), SIZE_T_UP(size));
}

HPy ctx_Unicode_DecodeFSDefault_jni(HPyContext *ctx, const char *v)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Unicode_DecodeFSDefault, PTR_UP(v));
}

HPy ctx_Unicode_DecodeFSDefaultAndSize_jni(HPyContext *ctx, const char *v, HPy_ssize_t size)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Unicode_DecodeFSDefaultAndSize, PTR_UP(v), SIZE_T_UP(size));
}

HPy ctx_Unicode_EncodeFSDefault_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Unicode_EncodeFSDefault, HPY_UP(h));
}

HPy_UCS4 ctx_Unicode_ReadChar_jni(HPyContext *ctx, HPy h, HPy_ssize_t index)
{
    return DO_UPCALL_HPY_UCS4(CONTEXT_INSTANCE(ctx), ctx_Unicode_ReadChar, HPY_UP(h), SIZE_T_UP(index));
}

HPy ctx_Unicode_DecodeASCII_jni(HPyContext *ctx, const char *s, HPy_ssize_t size, const char *errors)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Unicode_DecodeASCII, PTR_UP(s), SIZE_T_UP(size), PTR_UP(errors));
}

HPy ctx_Unicode_DecodeLatin1_jni(HPyContext *ctx, const char *s, HPy_ssize_t size, const char *errors)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Unicode_DecodeLatin1, PTR_UP(s), SIZE_T_UP(size), PTR_UP(errors));
}

HPy ctx_Unicode_FromEncodedObject_jni(HPyContext *ctx, HPy obj, const char *encoding, const char *errors)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Unicode_FromEncodedObject, HPY_UP(obj), PTR_UP(encoding), PTR_UP(errors));
}

HPy ctx_Unicode_InternFromString_jni(HPyContext *ctx, const char *str)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Unicode_InternFromString, PTR_UP(str));
}

HPy ctx_Unicode_Substring_jni(HPyContext *ctx, HPy obj, HPy_ssize_t start, HPy_ssize_t end)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Unicode_Substring, HPY_UP(obj), SIZE_T_UP(start), SIZE_T_UP(end));
}

int ctx_List_Check_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_List_Check, HPY_UP(h));
}

HPy ctx_List_New_jni(HPyContext *ctx, HPy_ssize_t len)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_List_New, SIZE_T_UP(len));
}

int ctx_List_Append_jni(HPyContext *ctx, HPy h_list, HPy h_item)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_List_Append, HPY_UP(h_list), HPY_UP(h_item));
}

int ctx_Dict_Check_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_Dict_Check, HPY_UP(h));
}

HPy ctx_Dict_New_jni(HPyContext *ctx)
{
    return DO_UPCALL_HPY0(CONTEXT_INSTANCE(ctx), ctx_Dict_New);
}

HPy ctx_Dict_Keys_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Dict_Keys, HPY_UP(h));
}

HPy ctx_Dict_GetItem_jni(HPyContext *ctx, HPy op, HPy key)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Dict_GetItem, HPY_UP(op), HPY_UP(key));
}

int ctx_Tuple_Check_jni(HPyContext *ctx, HPy h)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_Tuple_Check, HPY_UP(h));
}

HPy ctx_Tuple_FromArray_jni(HPyContext *ctx, HPy items[], HPy_ssize_t n)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Tuple_FromArray, LONG_UP(items), SIZE_T_UP(n));
}

int ctx_Slice_Unpack_jni(HPyContext *ctx, HPy slice, HPy_ssize_t *start, HPy_ssize_t *stop, HPy_ssize_t *step)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_Slice_Unpack, HPY_UP(slice), PTR_UP(start), PTR_UP(stop), PTR_UP(step));
}

HPy ctx_ContextVar_New_jni(HPyContext *ctx, const char *name, HPy default_value)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_ContextVar_New, PTR_UP(name), HPY_UP(default_value));
}

int ctx_ContextVar_Get_jni(HPyContext *ctx, HPy context_var, HPy default_value, HPy *result)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_ContextVar_Get, HPY_UP(context_var), HPY_UP(default_value), PTR_UP(result));
}

HPy ctx_ContextVar_Set_jni(HPyContext *ctx, HPy context_var, HPy value)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_ContextVar_Set, HPY_UP(context_var), HPY_UP(value));
}

HPy ctx_Import_ImportModule_jni(HPyContext *ctx, const char *name)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Import_ImportModule, PTR_UP(name));
}

HPy ctx_Capsule_New_jni(HPyContext *ctx, void *pointer, const char *name, HPyCapsule_Destructor destructor)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Capsule_New, PTR_UP(pointer), PTR_UP(name), LONG_UP(destructor));
}

void *ctx_Capsule_Get_jni(HPyContext *ctx, HPy capsule, _HPyCapsule_key key, const char *name)
{
    return (void *)DO_UPCALL_PTR(CONTEXT_INSTANCE(ctx), ctx_Capsule_Get, HPY_UP(capsule), INT_UP(key), PTR_UP(name));
}

int ctx_Capsule_IsValid_jni(HPyContext *ctx, HPy capsule, const char *name)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_Capsule_IsValid, HPY_UP(capsule), PTR_UP(name));
}

int ctx_Capsule_Set_jni(HPyContext *ctx, HPy capsule, _HPyCapsule_key key, void *value)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_Capsule_Set, HPY_UP(capsule), INT_UP(key), PTR_UP(value));
}

HPy ctx_FromPyObject_jni(HPyContext *ctx, cpy_PyObject *obj)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_FromPyObject, PTR_UP(obj));
}

cpy_PyObject *ctx_AsPyObject_jni(HPyContext *ctx, HPy h)
{
    return (cpy_PyObject *)DO_UPCALL_PTR(CONTEXT_INSTANCE(ctx), ctx_AsPyObject, HPY_UP(h));
}

HPyListBuilder ctx_ListBuilder_New_jni(HPyContext *ctx, HPy_ssize_t initial_size)
{
    return DO_UPCALL_HPYLISTBUILDER(CONTEXT_INSTANCE(ctx), ctx_ListBuilder_New, SIZE_T_UP(initial_size));
}

void ctx_ListBuilder_Set_jni(HPyContext *ctx, HPyListBuilder builder, HPy_ssize_t index, HPy h_item)
{
    DO_UPCALL_VOID(CONTEXT_INSTANCE(ctx), ctx_ListBuilder_Set, HPY_LIST_BUILDER_UP(builder), SIZE_T_UP(index), HPY_UP(h_item));
}

HPy ctx_ListBuilder_Build_jni(HPyContext *ctx, HPyListBuilder builder)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_ListBuilder_Build, HPY_LIST_BUILDER_UP(builder));
}

void ctx_ListBuilder_Cancel_jni(HPyContext *ctx, HPyListBuilder builder)
{
    DO_UPCALL_VOID(CONTEXT_INSTANCE(ctx), ctx_ListBuilder_Cancel, HPY_LIST_BUILDER_UP(builder));
}

HPyTracker ctx_Tracker_New_jni(HPyContext *ctx, HPy_ssize_t size)
{
    return DO_UPCALL_HPYTRACKER(CONTEXT_INSTANCE(ctx), ctx_Tracker_New, SIZE_T_UP(size));
}

int ctx_Tracker_Add_jni(HPyContext *ctx, HPyTracker ht, HPy h)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_Tracker_Add, HPY_TRACKER_UP(ht), HPY_UP(h));
}

void ctx_Tracker_ForgetAll_jni(HPyContext *ctx, HPyTracker ht)
{
    DO_UPCALL_VOID(CONTEXT_INSTANCE(ctx), ctx_Tracker_ForgetAll, HPY_TRACKER_UP(ht));
}

void ctx_Tracker_Close_jni(HPyContext *ctx, HPyTracker ht)
{
    DO_UPCALL_VOID(CONTEXT_INSTANCE(ctx), ctx_Tracker_Close, HPY_TRACKER_UP(ht));
}

void ctx_Field_Store_jni(HPyContext *ctx, HPy target_object, HPyField *target_field, HPy h)
{
    DO_UPCALL_VOID(CONTEXT_INSTANCE(ctx), ctx_Field_Store, HPY_UP(target_object), PTR_UP(target_field), HPY_UP(h));
}

HPy ctx_Field_Load_jni(HPyContext *ctx, HPy source_object, HPyField source_field)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Field_Load, HPY_UP(source_object), HPY_FIELD_UP(source_field));
}

void ctx_ReenterPythonExecution_jni(HPyContext *ctx, HPyThreadState state)
{
    DO_UPCALL_VOID(CONTEXT_INSTANCE(ctx), ctx_ReenterPythonExecution, HPY_THREAD_STATE_UP(state));
}

HPyThreadState ctx_LeavePythonExecution_jni(HPyContext *ctx)
{
    return DO_UPCALL_HPYTHREADSTATE0(CONTEXT_INSTANCE(ctx), ctx_LeavePythonExecution);
}

void ctx_Global_Store_jni(HPyContext *ctx, HPyGlobal *global, HPy h)
{
    DO_UPCALL_VOID(CONTEXT_INSTANCE(ctx), ctx_Global_Store, PTR_UP(global), HPY_UP(h));
}

HPy ctx_Global_Load_jni(HPyContext *ctx, HPyGlobal global)
{
    return DO_UPCALL_HPY(CONTEXT_INSTANCE(ctx), ctx_Global_Load, HPY_GLOBAL_UP(global));
}

void ctx_Dump_jni(HPyContext *ctx, HPy h)
{
    DO_UPCALL_VOID(CONTEXT_INSTANCE(ctx), ctx_Dump, HPY_UP(h));
}

int ctx_Type_CheckSlot_jni(HPyContext *ctx, HPy type, HPyDef *value)
{
    return DO_UPCALL_INT(CONTEXT_INSTANCE(ctx), ctx_Type_CheckSlot, HPY_UP(type), PTR_UP(value));
}

