name: build-windows-amd64-wheels
'on':
  workflow_dispatch:
    inputs:
      packages:
        type: string
        description: Pkgs to build (comma-separated, empty for all)
        required: false
      graalpy_url:
        type: string
        description: GraalPy download url
        required: true
jobs:
  build_wheels:
    runs-on: windows-latest
    env:
      PACKAGES_TO_BUILD: ${{ inputs.packages }}
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Checkout
        uses: actions/checkout@main
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: "-A warnings -A unexpected-cfgs -A unused-macros -A static-mut-refs -A unused-variables -A unused-imports"
          cache: false
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Build wheels
        run: |
          $env:PATH+=";C:\Program Files\Git\usr\bin"
          python3 scripts/wheelbuilder/build_wheels.py ${{ inputs.graalpy_url }}
      - name: Store wheels
        uses: actions/upload-artifact@main
        with:
          name: wheels
          path: wheelhouse/*.whl
          if-no-files-found: error
