name: build-linux-aarch64-wheels
'on':
  workflow_dispatch:
    inputs:
      packages:
        type: string
        description: Pkgs to build (comma-separated, empty for all)
        required: false
      graalpy_url:
        type: string
        description: GraalPy download url
        required: true
jobs:
  build_wheels:
    runs-on:
      - self-hosted
      - Linux
      - ARM64
    container: quay.io/pypa/manylinux_2_28_aarch64
    env:
      PACKAGES_TO_BUILD: ${{ inputs.packages }}
    steps:
      - name: Install dependencies
        run: |
          dnf install -y epel-release
          crb enable
          dnf makecache --refresh
          dnf module install -y nodejs:18
          dnf install -y /usr/bin/patch
      - name: Checkout
        uses: actions/checkout@main
      - name: Build wheels
        run: |
          python3 -m venv wheelbuilder_venv
          export PIP_EXTRA_INDEX_URL=https://pypi.org/simple
          wheelbuilder_venv/bin/python3 scripts/wheelbuilder/build_wheels.py ${{ inputs.graalpy_url }}
      - name: Build wheels
        run: python3 scripts/wheelbuilder/build_wheels.py ${{ inputs.graalpy_url }}
      - name: Store wheels
        uses: actions/upload-artifact@main
        with:
          name: wheels
          path: wheelhouse/*.whl
          if-no-files-found: error
